### ISSUE TITLE
rename HtmlError to HttpError

### ISSUE THREAD

**Issue by DrRibosome** [dask/gcsfs#105]
This may be a bit pedantic, but gcsfs errors are related to the http transfer protocol, not html. It would make more sense for them to be called HttpError instead

https://github.com/dask/gcsfs/blob/f64f9c54cf2522da222186b33abeafcfbff2dcc0/gcsfs/utils.py#L91

**Comment by martindurant** [comment]
Agreed, happy to see a PR, if you have time.
