### ISSUE TITLE
Error in Refresh token

### ISSUE THREAD

**Issue by Chostakovis** [dask/gcsfs#108]
Hello all,
I'm trying to make a refresh token call using 
oauth2Client.refreshAccessToken(function(err, tokens) {
  // your access_token is now refreshed and stored in oauth2Client
  // store these new tokens in a safe place (e.g. database)
});

But I'm receiving the following error
 { error: 'deleted_client',
        error_description: 'The OAuth client was deleted.' } },
  code: '401' }

Does anybody how to handle this error?

Thank you

**Comment by martindurant** [comment]
What token are you refreshing, I don't understand. Is this directly related to gcsfs, or something else.

Maybe related, the client identity used by gcsfs for its own auth (e.g., when using browser credentials) does expire every six months, so updating your version of gcsfs may fix this.

**Comment by Chostakovis** [comment]
Hi, @martindurant ...
I'm trying to refresh the refresh token as it expires in 1 hour so I'm trying to refresh it on every call.
The complete code bellow:

const { google } = require('googleapis');
var oauth2Client = google.auth.OAuth2;
var CLIENT_ID = 'xxxxxx;
var CLIENT_SECRET = 'xxxxxx';
var access_token = 'xxxxxx'
var refresh_token ='xxxxx'

var BASE_URL = 'http://localhost:4000';
var REDIRECT_URL = 'http://localhost:3000/oauth2Callback';
var oauth2Client = new google.auth.OAuth2(CLIENT_ID, CLIENT_SECRET,REDIRECT_URL);

const credentials = {access_token: access_token, refresh_token: refresh_token};
oauth2Client.setCredentials(credentials);

oauth2Client.refreshAccessToken(function(err, tokens) {
  //console.log(err);
  // your access_token is now refreshed and stored in oauth2Client
  // store these new tokens in a safe place (e.g. database)
});

**Comment by martindurant** [comment]
I'm sorry, I still don't understand. gcsfs does not require you to refresh google tokens it does that itself. Your code doesn't mention gcsfs: perhaps you wanted to post this in another repo?
