### ISSUE TITLE
Missing information how to copy files to GCS

### ISSUE THREAD

**Issue by hnykda** [dask/gcsfs#112]
Hey, 
this is the current documentation:

![image](https://user-images.githubusercontent.com/2741256/46961470-22629c00-d0a1-11e8-94ad-11497174bcfd.png)

and it actually misses one of the most common usecases and that is putting a file on the storage (which is `put` I hope).

**Comment by martindurant** [comment]
Yes, you are quite right, there seems to be less in the docstrings than there ought to be or, honestly, than I remember there being. I would be very grateful if you were to supply some, and the online documentation would update automatically.

Interestingly, I do have generic documentation for all of the file-system methods in [fsspec](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py), but gcsfs has not yet been ported to subclass from the spec and gain the automatic documentation.

**Comment by martindurant** [comment]
For reference, this [very similar API](https://s3fs.readthedocs.io/en/latest/api.html) appears complete

**Comment by hnykda** [comment]
Hah, you were faster.

**Comment by martindurant** [comment]
:)

**Comment by laniakea** [comment]
Is there an example of how to copy a file from one address to another address?

**Comment by martindurant** [comment]
Sorry, @laniakea , what would you like to do? I encourage you to look at the API documentation and the docstrings. Perhaps you want `GCSFileSystem.cp`? or `cp_file`?

**Comment by laniakea** [comment]
Thanks cp worked but cp_file didn't. Could you please make the documentation more "searchable". I couldn't initially find any information about cp when I searched for copy. Thank you for your good work.

**Comment by martindurant** [comment]
`gcs.copy` and `gcs.cp` are aliased, both have a minimal docstring. You are probably right that the API documentation page and examples could be greatly improved and expanded. Are you interested in helping? In what way did `cp_file` not work?
