### ISSUE TITLE
Req: specific the Content-Type of the upload

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#119]
It would be useful to specify the content-type when write to a file, especially if text/plain as browser can render without saving and opening outside.

Requires `GCSFile().open()` to accept, in `wt` or `wb` mode only, an optional `content-type` argument, which is passed to either `simple upload` or `resumable upload` (initialize only).

**Comment by yiga2** [comment]
It's useful for quickly checking the content for troubleshooting, in a browser (through the G console UI) but also the mobile Cloud Console app.

While we are at it, could you add 'content-encoding', same benefit if the content is gzipped text (browser/app decompresses on the fly) - see https://cloud.google.com/storage/docs/transcoding. 
`None` as default.

**Comment by martindurant** [comment]
It would be fine to add content-type and content-encoding to open() and put(). Indeed. maybe arbitrary header parameters could be passed through.
Would you have time to attempt this? Is the documentation clear on how to create VCR recordings for tests?

**Comment by yiga2** [comment]
Sure thing - I will make time on Monday and will read the VCR stuff.

**Comment by jmwoloso** [comment]
@yiga2 any progress on this?

**Comment by jmwoloso** [comment]
i think this is close to being available natively in `gcsfs` already after some experimentation.

you _can_ pass `metadata` via the `open` method and _it does_ get passed along to GCS, however, it doesn't do any overwriting (just duplicating; see screenshot below). I haven't looked at the `gcsfs` implementation yet, but seems like we should be able to pass in any of the `metadata` to the underlying library as headers and/or supported arguments if available.

```
import json
import gcsfs

fs = gcsfs.GCSFileSystem()
j = json.dumps({"success": True})

with open("path_to_bucket/_blob_name.json", "w", metadata={"Content-Type": "application/json"}) as f:
    f.write(j)
```

looking at the file metadata in the GCS bucket we can see the metadata was passed through but it didn't overwrite the `Content-Type` parameter, instead it was just duplicated.

![metadata](https://user-images.githubusercontent.com/7530947/49821844-a7cc9a80-fd38-11e8-9235-7cf9dec779a3.png)

**Comment by yiga2** [comment]
@jmwoloso this is not a duplicate. "your" content-type is custom metadata and is stored actually as `x-goog-meta-Content-Type`. You can pass custom metadata as you did but setting so-called fixed-key metadata require a minor enhancement.

**Comment by martindurant** [comment]
@yiga2 , were you planning on submitting a PR to deal with this?

**Comment by arpit1997** [comment]
@martindurant @yiga2 Can I submit a PR for this?

**Comment by martindurant** [comment]
@arpit1997 , please do! 
Let me know if you have trouble figuring out how to generate tests with vcrpy.

**Comment by arpit1997** [comment]
@martindurant Can you please review the PR? I am not familiar with vcrpy and tests are failing on travis. Can you check and let me know the reason around it?

**Comment by martindurant** [comment]
How to record new tests: https://gcsfs.readthedocs.io/en/latest/developer.html#testing-and-vcr
