### ISSUE TITLE
Service account token, authorization error if passed as dict object

### ISSUE THREAD

**Issue by VMois** [dask/gcsfs#120]
I have created a service account to limit access to a bucket. Using gcloud I have generated a key json file that looks like this:

```json
{
  "type": "service_account",
  "project_id": "---",
  "private_key_id": "---",
  "private_key": "---",
  "client_email": "--",
  "client_id": "---",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "---"
}
```

I have tried simple test for reading bucket:

```python
import gcsfs

fs = gcsfs.GCSFileSystem(
    project='project',
    token='/home/<user>/key.json'
)

print(fs.ls('bucket'))

```

And it works as expected with properly permissions etc. But, now, I want to read a json file as a python dict and pass it as a token. New code:

```python
import gcsfs
import json

key_file = open('/home/<user>/key.json', 'r')
key = json.load(key_file)

fs = gcsfs.GCSFileSystem(
    project='project',
    token=key
)

print(fs.ls('bucket'))
``` 

During execution I received the following error:
```
Traceback (most recent call last):
  File "/home/vmois/gstorage_test.py", line 10, in <module>
    token=key
  File "/home/vmois/python-venv/dask/lib/python3.6/site-packages/gcsfs/core.py", line 302, in __init__
    self.connect(method=token)
  File "/home/vmois/python-venv/dask/lib/python3.6/site-packages/gcsfs/core.py", line 421, in connect
    self._connect_token(method)
  File "/home/vmois/python-venv/dask/lib/python3.6/site-packages/gcsfs/core.py", line 385, in _connect_token
    credentials = self._dict_to_credentials(token)
  File "/home/vmois/python-venv/dask/lib/python3.6/site-packages/gcsfs/core.py", line 356, in _dict_to_credentials
    None, refresh_token=token['refresh_token'],
KeyError: 'refresh_token'
```

I'm using the same file but in different formats. Can we somehow improve token handling?

I think some changes in  `_connect_token` method. Line 384 we can add check if a token is service account like on line 378.

**Comment by martindurant** [comment]
Yes, you are quite right: `_connect_token` attempts the service account route only if the input is a string (i.e., a file). The method `service_account.Credentials.from_service_account_info` (as opposed to `from_service_account_file`) would be the one to call when passing a dict.

**Comment by VMois** [comment]
Should I submit a PR to add checking if dict is service account? I can do it today/tomorrow.

What about tests? Should I include them?

**Comment by VMois** [comment]
PR is merged, I'm closing the issue. Thanks for the help.
