### ISSUE TITLE
Appending to Metadata 

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#125]
Since `setxattrs` only works for replacement, I tried the below to append instead but metadata got deleted after !
`a=fs.info('bucket/file')['metadata']`
`fs.setxattrs('bucket/file', kwargs={'test': 'me', **a} )`

Any idea why ?

**Comment by yiga2** [comment]
Closing as I figure it out the right syntax: `**{'test': 'me', **a}`
Will actually make a PR out of it for an enhanced version:

- multiple blobs update in one call
- use `patch` instead of `put`
- allow other fixed meta settings e.g. content-type/-encoding

**Comment by martindurant** [comment]
You could do
```
a = fs.info('bucket/file')['metadata']
a.update({'test': 'me', ...})
fs.setxattrs('bucket/file', **a)
```

**Comment by yiga2** [comment]
Thanks but the `put` method wipes out all existing metadata, including Content-type if it was set before. Best is to use 'patch' in my opinion, which does append or replace only what is sent.

**Comment by martindurant** [comment]
I don't know about PUT versus PATCH, feel free to experiment
