### ISSUE TITLE
Logging Level Configuration

### ISSUE THREAD

**Issue by dillonjohnson** [dask/gcsfs#126]
This is not really a bug, more of a question.

I am wondering if there is a way to set the logging level within `gcsfs`.

We are not interested in having the logging level at DEBUG in all of processes. We mostly use DEBUG level locally for testing and debugging an issue.

Currently we are using a workaround, but I was curious if this is by design or if there is another way around this.

This is the current workaround we are using to set the logging level higher.
```
logging.getLogger(__name__).setLevel(level=logging.INFO)
```

Thanks in advance!

**Comment by martindurant** [comment]
You could use the environment variable GCSFS_DEBUG to set debug logging in some specific process.

**Comment by dillonjohnson** [comment]
So that would make it where DEBUG is not the default?

Currently, we do not have that Environment Variable set, but it is still logging out as DEBUG. It's unexpected since this snippet

`DEBUG = os.environ.get('GCSFS_DEBUG', False)`

Defaults to False if not defined.

**Comment by dillonjohnson** [comment]
@martindurant Any help would be appreciated here.

**Comment by martindurant** [comment]
Yes, I am puzzled - you should not see DEBUG-level logging normally, and neither I not other users do. Something else must be happening on your system.

**Comment by dillonjohnson** [comment]
Well you are correct. It seems to be inconsistent behavior. Possibly related to when we use the tarfile library. We're puzzled as well. I will update if we figure anything out.

**Comment by dillonjohnson** [comment]
Thanks for helping. @martindurant I appreciate it!
