### ISSUE TITLE
Getting "The OAuth client was deleted" error on connection

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#13]
```python
In [1]: import gcsfs

In [2]: gcsfs.GCSFileSystem()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-d964e936fddf> in <module>()
----> 1 gcsfs.GCSFileSystem()

/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/gcsfs/core.py in __init__(self, project, access, token, block_size)
    158         self.access = access
    159         self.dirs = {}
--> 160         self.connect()
    161         self._singleton[0] = self
    162 

/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/gcsfs/core.py in connect(self, refresh)
    267                                 'refresh_token': data['refresh_token'],
    268                                 'grant_type': "refresh_token"})
--> 269                 validate_response(r, path)
    270                 data['timestamp'] = time.time()
    271                 data['access_token'] = r.json()['access_token']

/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/gcsfs/core.py in validate_response(r, path)
    104             raise ValueError("Bad Request: %s" % path)
    105         else:
--> 106             raise RuntimeError(msg)
    107 
    108 

RuntimeError: b'{\n "error": "deleted_client",\n "error_description": "The OAuth client was deleted."\n}\n'
```

Looking around on the internet, people seem to suggest that I enable OAuth on my account.  This seems odd though because this didn't seem to be necessary before.  Any thoughts on what might be going on?

**Comment by martindurant** [comment]
Google seems to have cancelled the client access ID used by gcsfs, which is required for the "device code" method of creating a token. Is this six months?
Alternatively, it may be that your refresh token is six month old, in which case you should be able to login again using the google CLI and pass the token JSON file from there `token="path/to.json"`.
This is needed in the case that you don't already have a refresh token in your gcsfs cache, or supply a token/client directly provided by google, which comes with its own client ID. Note that you probably need a `"project="` at instantiation. I think the default is set to `""`, and you are not getting the appropriate warning.

I can create another client id for the device code, and have tested this works, but not immediately sure how to propagate this as a fix for everyone.

**Comment by mrocklin** [comment]
> I can create another client id for the device code, and have tested this works, but not immediately sure how to propagate this as a fix for everyone.

Does this mean that the `not_secret` data in gcsfs is what expired?  If so then there must be some way to make this more durable.  Short term would a release with a new code work?

**Comment by martindurant** [comment]
Exactly.
Yes, an immediate release with a new code would work, but I can't thing of a way to prevent this in the future, except to have a new code for every release, every three months or less. For most users, they would need this once or nonce.
I think the cached refresh tokens may also expire, and there is no check for this - I don't know if it would give the same error.

**Comment by mrocklin** [comment]
Can we periodically update the same token to keep it alive?

**Comment by mrocklin** [comment]
Short term, a gcsfs release would be helpful.  The upcoming Strata demo relies on this.

**Comment by martindurant** [comment]
I can certainly to that today. 
To be sure, though, are you generally providing a project= (or is this defined by environment variable?), and/or token='cloud'?
