### ISSUE TITLE
cache_timeout default is a bit of a landmine

### ISSUE THREAD

**Issue by JohnEmhoff** [dask/gcsfs#138]
The default caching behavior (that is, to have it enabled) was a pretty big source of confusion for me, causing all sorts of odd behavior in production but not in testing. Would you consider disabling all caching by default? I know it's simple enough to pass `cache_timeout=0`, but this is for the next person!

**Comment by martindurant** [comment]
I'm sorry you were bit by stale filelistings caches. Can I ask what you were doing when this became an issue? Operations that add/remove entries from gcsfs itself should invalidate caches and for a reload when you next list.
I think, that for most other users, the current behaviour is the one wanted: listing directories can be expensive, and those listings are not generally expected to change.

**Comment by JohnEmhoff** [comment]
I was using gcsfs in a service that would receive a notification that a set of files have been created on GCS. Since they were created externally and not by the local gcsfs, it wasn't in the cache -- I feel like this is not an uncommon pattern?

I agree that directory listing can be expensive, but I would just expect that caching to be done at the application layer.

**Comment by martindurant** [comment]
Not sure what to say - the caching here and in s3fs was created in response to applications, particularly within Dask, where the file listing was significantly making operations slower. Typically, the data is written once, and then static, or gcsfs itself is doing the writing. 
Given that the default has been the way it is for quite some time, I would need a lot of convincing that your situation, with data coming from a third party, is the common one.

**Comment by JohnEmhoff** [comment]
Okay, I understand that changing probably has a fairly high bar. I'm just surprised in this day of distributed applications it hasn't come up more!

Anywhoo, thanks for the nice library -- much nicer than the google provided module.
