### ISSUE TITLE
first character is being stripped from sub-paths

### ISSUE THREAD

**Issue by rabernat** [dask/gcsfs#140]
This is a bizarre issue, but bear with me.

You may verify for yourself that following gcs object exists and is publicly readable: https://storage.googleapis.com/pangeo-data/CMIP6-3hr/IPSL.IPSL-CM6A-LR.historical.3hr.gr/huss/.zarray

Now let me try to find it using gcsfs:
```python
import gcsfs
gcs = gcsfs.GCSFileSystem(token='anon')
gcsmap = gcsfs.GCSMap('/pangeo-data/CMIP6-3hr/IPSL.IPSL-CM6A-LR.historical.3hr.gr', gcs=gcs)
list(gcsmap.keys())
```

```
['zattrs',
 'zgroup',
 'zmetadata',
 'eight/.zarray',
 'eight/.zattrs',
 'eight/0',
 'uss/.zarray',
 'uss/.zattrs',
...
```

You can see that the first letter (`h` in this case) is being stripped out of the path. This makes it impossible to find the objects. This is pretty critical if you ask me!

I'm using gcsfs version 0.2.1.

**Comment by martindurant** [comment]
This is happening because of silently removing the leading "/" in the path, so the apparent root path's length is one longer than would otherwise be thought. The following works:
```
import gcsfs
gcs = gcsfs.GCSFileSystem(token='anon')
gcsmap = gcsfs.GCSMap('pangeo-data/CMIP6-3hr/IPSL.IPSL-CM6A-LR.historical.3hr.gr', gcs=gcs)
list(gcsmap.keys())
```

Obviously the behaviour should *not* depend on whether there is a leading "/".

**Comment by rabernat** [comment]
Dropping the leading slash fixes it!

Glad it's an easy fix...but yes, I agree that it is confusing that the presence / absence of the leading "/"  can lead to this.
