### ISSUE TITLE
gcsfs.open encoding capability

### ISSUE THREAD

**Issue by philip-zelichenko** [dask/gcsfs#142]
I couldn't find anything in the documentation, but if I understand correctly there isn't support to predefining a sepcific encoding, as possible through the native python libraries.
![image](https://user-images.githubusercontent.com/16638019/55496895-eabac280-55f4-11e9-875d-b41249aa6afe.png)

**Comment by martindurant** [comment]
You could always open in binary mode and wrap with TextIOWrapper. You may be interested in seeing what `fsspec.open` does (aka filesystem-spec, which has partial support for gcsfs). Given the progress there and the eventual plan to have all of these filesystems depend on fsspec, I would recommend against implementing a full text mode in gcsfs right now.

**Comment by philip-zelichenko** [comment]
thanks @martindurant, is there any other line by line google cloud storage reader that you recommend using that does support pre defined encoding?

**Comment by martindurant** [comment]
I have no idea, sorry.
If you *did* want to implement encoding here, I promise to review it. Actually checking the code of `open()`, would be trivial.

**Comment by philip-zelichenko** [comment]
@martindurant I see that the code op open is wrapped with io.TextIOWrapper which supports encoding. Is there a reason not to use it there?

**Comment by martindurant** [comment]
That's why I said it would be a trivial fix, if you wanted to implement it :)

**Comment by martindurant** [comment]
This is now fixed in fsspec
