### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by pakelley** [dask/gcsfs#148]
I was hoping to use the recursive `get`/`put` functionality that was implemented since version 0.2.1, and I was curious if there are plans for a release any time soon.

Funny(ish) story: I actually implemented this in hopes of being a `gcsfs` contributor then realized it was already in master, just not released! 😅 Not my brightest moment haha.

Thank you for all of the work on this useful library 🙂

**Comment by martindurant** [comment]
https://pypi.org/project/gcsfs/0.2.2/#files and coming soon to conda-forge, probably by this evening
