### ISSUE TITLE
URI's protocol is not removed in GCSFileSystem.get

### ISSUE THREAD

**Issue by pakelley** [dask/gcsfs#149]
I've been using `GCSFileSystem.get` with `recursive=True`, and ran into some unexpected (to me) behavior: the first few characters of the local file names were missing. It looks like this happens when a `gs://` protocol is in the path.

After some digging, I realized that the recursive `get` is using `GCSFileSystem.walk` to get the paths to copy (which returns canonicalized paths from `gcsfs.core.norm_path`), but then it uses the length of original remote path (including the `gs://` protocol) to piece together the output paths.

My question is: Is it required that there is no protocol in the path passed to `get`?
If not, I'm happy to open up a PR that simply uses `norm_path` in `get`. Wanted to make sure I'm not just using the library in an unexpected way first though.

**Comment by martindurant** [comment]
Should be easy to correct inline https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L932 ? Of, you could simply `rpath = norm_path(rpath)` at the start of the function?
Would you be interested in submitting a PR with test?

**Comment by pakelley** [comment]
That's exactly what I was thinking 👍 
And yep, I can make a PR a bit later today
