### ISSUE TITLE
DaskGCSFileSystem Credential de/serialization

### ISSUE THREAD

**Issue by jiajie-chen** [dask/gcsfs#155]
When attempting use gcsfs with Dask's distributed local cluster, authenticating with service account credentials, Dask throws the error: 
```
distributed.protocol.core - CRITICAL - Failed to Serialize
<... long traceback ...>
TypeError: ('Could not serialize object of type tuple.', "(<function read_json_file at 0x7f7060318840>, <dask.bytes.core.OpenFile object at 0x7f705c60e668>, 'records', True, (<class 'dict'>, [['dtype', False]]))")
```

I've traced this issue back to how Google's `google.oauth2.service_account.Credentials` uses `cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey` internally to sign tokens.
Because `RSAPrivateKey` is a `CompiledFFI` object, it needs special logic to de/serialize.
Dask's distributed protocol serializes gcsfs instances to pass to workers, so being able to serialize Credentials is needed for gcsfs to work with Dask.

**System Details:**
Python 3.6.8, running on Docker image `python:3.6`
`dask[complete]==1.2.0`
`distributed==1.28.1`
`gcsfs` from dask/gcsfs:master, commit `6852931`
`google-auth==1.6.3`
`cryptography==2.7`

**Steps to Recreate:**
Test the following code snippet:

```python
import dask
from dask import dataframe
from dask import distributed
import google.oauth2.service_account
import gcsfs

def run_copy_test(gcs_project, cred_key_path, gcs_src_json_uri, gcs_dst_json_uri):
    cluster = distributed.LocalCluster(dashboard_address=None)
    client = distributed.Client(cluster)
    with dask.config.set(scheduler=client):
        # use service_account.Credentials
        scopes = ["https://www.googleapis.com/auth/devstorage.full_control"]
        credentials = (
            google.oauth2.service_account.Credentials.from_service_account_file(
                cred_key_path, scopes=scopes)
        )
        storage_options = {
            "project": gcs_project,
            "token": credentials
        }
        # test loading and rewriting json file on GCS
        json_ddf = dataframe.read_json(
            gcs_src_json_uri,
            storage_options=storage_options
        )
        json_ddf.to_json(
            gcs_dst_json_uri,
            storage_options=storage_options
        )
    cluster.close()

if __name__ == "__main__":
    # This will throw errors
    run_copy_test(
        "PROJECT-ID",
        "/path/to/service_account/key.json",
        "gcs://path/to/json/file.json",
        "gcs://path/to/destination/folder"
    )
```

I've tested a fix on my fork [here](https://github.com/jiajie-chen/gcsfs/tree/fixes). It fixes the issues with Dask, by using a custom Pickler and Unpickler to handle serializing credentials.
However, I'm handling this by converting `RSAPrivateKey`s to unencrypted PEM bytestrings, which is insecure. Ideally the pickling logic could encrypt serialized credentials using a symmetric key, which a user can pass into the `GCSFileSystem` constructor, defining an environment variable, or some other logic.

**Comment by martindurant** [comment]
You probably *don't* generally want to send your credentials around like that - but you could use dict form to do it, if you wanted to. Instead, you want the "google" method of authentication to be able to find the correct credentials on each worker. Figuring out how to get that to find your service credentials as opposed to trying to find user credentials is the problem.

**Comment by jiajie-chen** [comment]
True, I think in that case gcsfs should avoid serializing credentials entirely - perhaps by checking if `token` is a non-anonymous `Credentials` and throwing an error, similar to how s3fs handles passed-in sessions. AFAIK non-service-account credential `token`s are still serialized by `GCSFileSystem`.

I guess my use case is weird, in that we're loading a `Credentials` object from Airflow and then handing it off to Dask. I think a better solution is to coordinate a way to distribute service account keys from Airflow to Dask.
