### ISSUE TITLE
GCSFile does not inherit from IOBase

### ISSUE THREAD

**Issue by ElliotSilver** [dask/gcsfs#157]
I'm working with a module that makes a test to see if an argument passed to a function is the name of a file, or a file-like object. The test is done by checking if the argument is an instance of IOBase. Since GCSFile is not inherited from IOBase, the test fails. It should be possible to structure GCSFile as a subclass of IOBase.

**Comment by martindurant** [comment]
Good idea!
I would implement this [here](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py#L761), since gcsfs will depend upon fsspec in the near future, and then we do not need to repeat ourselves.
