### ISSUE TITLE
Bug: `glob` mishandles paths with only "?"

### ISSUE THREAD

**Issue by kalugny** [dask/gcsfs#159]
Hi and thanks for a great package.

There's a bug in `GCSFileSystem.glob` because of the line:
```python
if '*' not in path:
    path = path.rstrip('/') + '/*'
```
in which if you don't have `*` in your pattern, the behavior is incorrect.

E.g.:
For a directory with files `text1.txt`, `text2.txt`, `text3.txt`, 
```python
fs = gcsfs.GCSFileSystem()
fs.glob('my-bucket/text?.txt')
```
returns `[]`

**Comment by kalugny** [comment]
And if we're already here, then the code also doesn't escape `.` in the path, which turns them into "every character" in the regex.
E.g.
```python
fs.glob('my-bucket/file.txt')
```
will also match `file7txt`

**Comment by kalugny** [comment]
BTW, instead of writing it yourself, you can use the builtin `glob` package:
https://docs.python.org/3/library/glob.html

This is what `gsutil` uses

**Comment by martindurant** [comment]
Please try this with the current master, which used the glob implementation from fsspec
