### ISSUE TITLE
Dependencies missing in conda recipe

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#16]
@quasiben and I conda-installed gcsfs in a fresh environment.  We found that we needed dask-core and toolz for things to function properly.

**Comment by martindurant** [comment]
gcsfs is supposed to work in isolation (see [here](https://github.com/dask/gcsfs/blob/master/gcsfs/dask_link.py#L55)), without dask - what did you mean "function properly"?

**Comment by mrocklin** [comment]
The following failed

```python
from gcsfs import GCSFileSystem
gcs = GCSFileSystem(token='cloud')
```

**Comment by quasiben** [comment]
This was installing into a vanilla python environment

**Comment by martindurant** [comment]
What did you see? I also started a new environment and had no problem, albeit with a local token rather that 'cloud'.

**Comment by quasiben** [comment]
the issue, it seemed, was that gcsfs depended on toolz and dask-core, neither of which I had in my env

**Comment by martindurant** [comment]
Tools is not mentioned anywhere in gcsfs, and the dask is imported within a function which is called in a try/except ImportError block, so I don't see how it can fail for you. What's the traceback?

**Comment by quasiben** [comment]
closing.  I can no longer reproduce
