### ISSUE TITLE
"ls" behavior change between 0.2.1 and 0.3.0?

### ISSUE THREAD

**Issue by JohnEmhoff** [dask/gcsfs#163]
It seems that in 0.2.1 the `ls` method will retrieve all items with a given prefix, while in 0.3.0 `ls` will only return directory-like entries. Is this an intended behavior change? It's obviously a breaking change, but either way I can't seem to find a workaround.

Here's 0.2.1 listing some files from one of the public GCP datasets:
```
$ pip freeze | grep gcsfs
gcsfs==0.2.1
$ python -q
>>> import gcsfs
>>> c = gcsfs.GCSFileSystem()
>>> c.ls('gs://gcp-public-data-landsat/index.csv')
['gcp-public-data-landsat/index.csv.gz-Z2HDRBNIWV', 'gcp-public-data-landsat/index.csv.gz-62ZC8HYJDE', 'gcp-public-data-landsat/index.csv.gz-BVVBYIFND0', ....]
```

And here's 0.3.0 doing the same listing and getting zero results:
```
$ pip freeze | grep gcsfs
gcsfs==0.3.0
$ python -q
>>> import gcsfs
>>> c = gcsfs.GCSFileSystem()
>>> c.ls('gs://gcp-public-data-landsat/index.csv')
[]
```

**Comment by martindurant** [comment]
That's correct - the previous behaviour was wrong! That is, the equivalent functionality on a local file-system would only list files within a directory, not all that happened to have that prefix.
If you wanted the previous listing, the easiest thing to do would be
```
fs.glob('gs://gcp-public-data-landsat/index.csv*')
```

**Comment by JohnEmhoff** [comment]
Huh, interesting. I know the previous behavior doesn't act like a "normal" filesystem but it's the abstraction GCS et al expose (and that I suppose gcsfs is trying to hide). It's also what the documentation very strongly implies -- it uses the word "prefix" the same way that the GCS / S3 docs do. Would you accept a doc pull request that clarifies?

**Comment by martindurant** [comment]
Yes, updating the docs is certainly needed, and I am aiming to get to it. If you have time, I would greatly appreciate it. I always found the s3/gcs docs confusing on this point, because prefix behaves differently when used on its own, versus in combination with a separator.

**Comment by JohnEmhoff** [comment]
Sorry one more thing -- so is it a bug that the listing below does not return the empty list as a local file system would?

```
>>> gcsfs._version.get_versions()['version']
'0.3.0'
>>> c.ls('gs://gcp-public-data-landsat/LM')
['gcp-public-data-landsat/LM01/', 'gcp-public-data-landsat/LM04/', 'gcp-public-data-landsat/LM03/', 'gcp-public-data-landsat/LM02/', 'gcp-public-data-landsat/LM05/']
```

**Comment by martindurant** [comment]
Hm, yes, going on my own argument, this should return an empty list.

**Comment by fbriol** [comment]
This new feature introduces a bug with pyarrow. Indeed, if we list the file `/root/a` where `a` is a directory, the function returns in addition to the parquet files the directory `a`. pyarrow throws an error because parquet files are mixed with directories (keys). Moreover, this error is silent because it is raised in a thread and is not caught correctly...

**Comment by martindurant** [comment]
Are you certain? gcsfs/tests/test_core.py::test_ls_touch , for example, seems to assert a case where this is not true. I have tried locally (master versions of fsspec and gcsfs) and do not find what you are seeing either:
```
In [180]: gcs.ls("mdtemp/oi")
Out[180]: ['mdtemp/oi/how']
```
(does not include "mdtemp/oi", whether or not using the terminal "/")

**Comment by fbriol** [comment]
A code that allows me to reproduce the error.

```python
import gcsfs
import gcsfs.core
import pyarrow.parquet as pq
```


```python
fs = gcsfs.GCSFileSystem()
df = pq.ParquetDataset("gs://pangeo-cnes/argo", filesystem=fs)
```


    ---------------------------------------------------------------------------

    IndexError                                Traceback (most recent call last)

    <ipython-input-2-b3d8fe4d14c5> in <module>
          1 fs = gcsfs.GCSFileSystem()
    ----> 2 df = pq.ParquetDataset("gs://pangeo-cnes/argo", filesystem=fs)
    

    /srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema, filters, metadata_nthreads, memory_map)
       1006 
       1007         if validate_schema:
    -> 1008             self.validate_schemas()
       1009 
       1010     def equals(self, other):


    /srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in validate_schemas(self)
       1038                 self.schema = self.common_metadata.schema
       1039             else:
    -> 1040                 self.schema = self.pieces[0].get_metadata().schema
       1041         elif self.schema is None:
       1042             self.schema = self.metadata.schema


    IndexError: list index out of range



```python
def ls(self, path, detail=False):
    """List objects under the given '/{bucket}/{prefix} path."""
    path = gcsfs.core.norm_path(path)

    if path in ['/', '']:
        if detail:
            return self._list_buckets()
        else:
            return self.buckets
    elif path.endswith("/"):
        return self._ls(path, detail)
    else:
        combined_listing = self._ls(path + "/", detail)
        if detail:
            combined_entries = dict(
                (l["name"], l) for l in combined_listing)
            combined_entries.pop(path + "/", None)
            return list(combined_entries.values())
        else:
            return list(set(combined_listing) - {path + "/"})
```


```python
gcsfs.core.GCSFileSystem.ls = ls
```


```python
gcsfs.__version__
```




    '0.3.0'




```python
fs = gcsfs.GCSFileSystem()
```


```python
df = pq.ParquetDataset("gs://pangeo-cnes/argo", filesystem=fs)
```


```python

```

**Comment by martindurant** [comment]
So it turns out that you have a real key which happens to have the same path as the directory you are trying to access:
```
In [189]: gcs.cat('gs://pangeo-cnes/argo/')
Out[189]: b'placeholder'
```

Note that this path shows up if you ls 'gs://pangeo-cnes/argo/' but not for 'gs://pangeo-cnes/argo' (without trailing "/").

**Comment by fbriol** [comment]
I don't quite understand the answer. If I enter `df = pq.ParquetDataset("gs://pangeo-cnes/argo/", filesystem=fs)` I have the same error.

**Comment by martindurant** [comment]
It would seem that pyarrow doesn't care about the final "/" but gcsfs does - as you can see by the difference in the output of ls with and without.
But the point is, there **is** an extra file in the bucket, and this is causing the error.

**Comment by fbriol** [comment]
The structure of my data is as follows: 
```
argo/
├── year=1995
│   ├── month=10
│   │   └── 8030c725b5ff42359fba4362719212b0.parquet
│   ├── month=11
│   │   └── c52e1e7984364915bec0f8bd8c77de89.parquet
│   ├── month=12
│   │   └── e91fe0ba3cdc4c96870c8451adff7f24.parquet
│   └── month=9
│       └── 155289ec32284c97b6f72ac1df7a3060.parquet
.../...
```
The files are only present in the sheets in the tree structure.

**Comment by fbriol** [comment]
This is the call to the system that causes the error:
```
>>> next(fs.walk("gs://pangeo-cnes/argo/year=2016/month=1"))
('pangeo-cnes/argo/year=2016/month=1',
 ['month=10','month=11','month=12'],
 ['58e2438c684d478f81958a3b366840a6.parquet'])
```

The "month=1" directory is listed and the function returns the file present in the directory and directories located at the same level as "month=1".

In the old version we have:
```
>>> next(fs.walk("gs://pangeo-cnes/argo/year=2016/month=1"))
('pangeo-cnes/argo/year=2016/month=1',
 [],
 ['58e2438c684d478f81958a3b366840a6.parquet'])
```

The "/" at the end of the path returns exactly the same result because fsspec starts by deleting it.....

**Comment by martindurant** [comment]
The true structure is, in fact:
```
argo/  <- file containing b'placeholder'
argo/
├── year=1995
│   ├── month=10
│   │   └── 8030c725b5ff42359fba4362719212b0.parquet
│   ├── month=11
│   │   └── c52e1e7984364915bec0f8bd8c77de89.parquet
│   ├── month=12
│   │   └── e91fe0ba3cdc4c96870c8451adff7f24.parquet
│   └── month=9
│       └── 155289ec32284c97b6f72ac1df7a3060.parquet
.../...
```

**Comment by fbriol** [comment]
It works! 
:+1:

**Comment by martindurant** [comment]
Alternate version in #179
