### ISSUE TITLE
Credentials check fails when using VPC Service Controls

### ISSUE THREAD

**Issue by leg100** [dask/gcsfs#164]
I tried using gcsfs on a VM, using its metadata credentials, in a project contained within a [VPC service perimeter](https://cloud.google.com/vpc-service-controls/docs/overview). gcsfs successfully fetches the credentials, but when it then goes onto [check the credentials by accessing a public GCS bucket](https://github.com/dask/gcsfs/blob/0.3.0/gcsfs/core.py#L412), it fails because the perimeter blocks access to Google APIs for other projects.

I'm aware you can disable the check, but this isn't straightforward in my case, because I'm using [pandas](https://github.com/pandas-dev/pandas/pull/20729) and it doesn't expose the relevant parameter that disables the check.

This may well trip other users using VPC service controls.

**Comment by martindurant** [comment]
The check should probably be omitted by default. Would you like to make the appropriate change in a PR?
