### ISSUE TITLE
GCSMap missing in version 0.3.0

### ISSUE THREAD

**Issue by cspencerjones** [dask/gcsfs#166]
If I run 
`import gcsfs`
`gcsfs.GCSMap`
I get the error message:
`module 'gcsfs' has no attribute 'GCSMap'`

I am able to run other gcsfs commands but GCSMap seems to be missing. I think this was not the case in version 0.2.1 but I have not been able to create an environment that's compatible with 0.2.1 in order to check this.

**Comment by martindurant** [comment]
You do not need to instantiate GCSMap any more. You can either use the `.get_mapper()` method of an GCSFileSystem instance, or `fsspec.get_mapper("gcs://...")`. If you want to subclass, the implementation is [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/mapping.py#L7).

**Comment by rabernat** [comment]
Translation

> You do not need to instantiate GCSMap any more.

You do not need to call `map = gcsfs.GCSMap('path', gcs=gsc`)` any more. This syntax has been [deprecated](https://en.wikipedia.org/wiki/Deprecation).

> You can either use the `.get_mapper()` method of an GCSFileSystem instance, or `fsspec.get_mapper("gcs://...")`

Instead, you do it like this:

```python
gcs = gcsfs.GCSFileSystem(...)
map = gcs.get_mapper()
ds = xr.open_zarr(map)
```

There is also a new convenience function in the new [filesystem-spec](https://filesystem-spec.readthedocs.io) package which allows you to skip the gcs part. Instead you just do

```python
map = fsspec.get_mapper("gcs://...")
ds = xr.open_zarr(map)
```

Under the hood, this function figures out you need to use GCSFileSystem (based on the `gcs://` prefix).

> If you want to subclass, the implementation is [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/mapping.py#L7).

[Subclass](https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)#Subclasses_and_superclasses) means to write a new filesystem-like object that inherits from these existing types. I'm not sure why we would want to do this here.

**Comment by mrocklin** [comment]
Could we reduce this further at some point 

### Before

```python
map = fsspec.get_mapper("gcs://...")
ds = xr.open_zarr(map)
```

### After

```python
ds = xr.open_zarr('gcs://...')
```

**Comment by rabernat** [comment]
That's probably a question for zarr. We discussed it in https://github.com/zarr-developers/zarr-python/issues/301. There is some hesitation to make fsspec a dependency.
