### ISSUE TITLE
GCSFileSystem.walk broken with kwarg `detail=true`

### ISSUE THREAD

**Issue by ahmedx2** [dask/gcsfs#168]
A project I recently joined recently upgraded from v0.2.3 to v0.3.0. I've been hunting a bug related to a change in the behavior of `GCSFileSystem.walk` described in some detail below. Before that, I'll say up front that my ultimate question is:

**What is the best way in v0.3.0 to get the same `"path"` and `"md5Hash"` information given by walk(path,detail=True) in v0.2.3?**

## Before: v0.2.3

Before upgrading, my the project code called `walk(path,detail=True)`. For reference, see what this returns when called on one of the public GCP datasets:

```python
>>> fs = gcsfs.GCSFileSystem()
>>> w = fs.walk('gs://gcp-public-data-landsat/index.csv.gz', detail=True)
>>> pprint.pprint(w)
[{'bucket': 'gcp-public-data-landsat',
  'contentType': 'application/octet-stream',
  'crc32c': '6p/Z1w==',
  'etag': 'CNT6gcy4ouQCEAE=',
  'generation': '1566887980858708',
  'id': 'gcp-public-data-landsat/index.csv.gz/1566887980858708',
  'kind': 'storage#object',
  'md5Hash': 'wvqmRKytddbPHfXC/ygYhg==',
  'mediaLink': 'https://www.googleapis.com/download/storage/v1/b/gcp-public-data-landsat/o/index.csv.gz?generation=1566887980858708&alt=media',
  'metageneration': '1',
  'name': 'index.csv.gz',
  'path': 'gcp-public-data-landsat/index.csv.gz',
  'selfLink': 'https://www.googleapis.com/storage/v1/b/gcp-public-data-landsat/o/index.csv.gz',
  'size': 601644439,
  'storageClass': 'STANDARD',
  'timeCreated': '2019-08-27T06:39:40.858Z',
  'timeStorageClassUpdated': '2019-08-27T06:39:40.858Z',
  'updated': '2019-08-27T06:39:40.858Z'}]
```

The project only uses the information keyed by `'path'` and `'md5Hash'`.

## After: v0.3.0

However, in version 0.3.0 the same method call returns a generator instead of a list:

```python
>>> fs = gcsfs.GCSFileSystem()
>>> w = fs.walk('gs://gcp-public-data-landsat/index.csv.gz', detail=True)
>>> pprint.pprint(w)
<generator object AbstractFileSystem.walk at 0x7f0e9e005938>
```

If you try to convert it to a list, an exception is raised:

```python
>>> list(w)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahmed/COLGATE/env/lib/python3.6/site-packages/fsspec/spec.py", line 338, in walk
    listing = self.ls(path, True, **kwargs)
TypeError: ls() got multiple values for argument 'detail'
```

Weirdly enough, in contrast, conversion to a list via list comprehension gives an empty sequence:

```python
>>> [x for x in w]
[]
```

As does converting to a tuple:

```python
>>> tuple(w)
()
```

The documentation for v0.3.0 *is* updated to no longer list an optional `detail` argument for `walk`. Still, I need functionality equivalent to the v0.2.3 version of `walk(path, detail=True)` i.e. I need the `"path"` and `"md5Hash"` information for each file below `path`.

I'm not sure if the new `ls` is functionality equivalent to the old `walk`, but I've tried instead using `ls(path,detail=True)`: 

```python
>>> l = fs.ls('gs://gcp-public-data-landsat/index.csv.gz', detail=True)
>>> pprint.pprint(l)
[{'bucket': 'gcp-public-data-landsat',
  'contentType': 'application/octet-stream',
  'crc32c': '6p/Z1w==',
  'etag': 'CNT6gcy4ouQCEAE=',
  'generation': '1566887980858708',
  'id': 'gcp-public-data-landsat/index.csv.gz/1566887980858708',
  'kind': 'storage#object',
  'md5Hash': 'wvqmRKytddbPHfXC/ygYhg==',
  'mediaLink': 'https://www.googleapis.com/download/storage/v1/b/gcp-public-data-landsat/o/index.csv.gz?generation=1566887980858708&alt=media',
  'metageneration': '1',
  'name': 'gcp-public-data-landsat/index.csv.gz',
  'selfLink': 'https://www.googleapis.com/storage/v1/b/gcp-public-data-landsat/o/index.csv.gz',
  'size': 601644439,
  'storageClass': 'STANDARD',
  'timeCreated': '2019-08-27T06:39:40.858Z',
  'timeStorageClassUpdated': '2019-08-27T06:39:40.858Z',
  'type': 'file',
  'updated': '2019-08-27T06:39:40.858Z'}]
````

It looks like this is returning the desired info, where the `"md5Hash"` key is the same and there is a `"name"` key instead of `"path"`. Is this correct?

**Comment by martindurant** [comment]
I don't believe that walk should work like this, since the builtin version explicitly returns an iterator of tuples. You could propose this change, instead, for how `find()` works, which is like the previous version of `walk`.
