### ISSUE TITLE
gcsfs returns wrong number of rows

### ISSUE THREAD

**Issue by Kornel** [dask/gcsfs#170]
When reading a file with gcsfs (through pandas but that's not a factor here) I get a wrong number of rows.

To reproduce:
1. Download https://drive.google.com/file/d/1X306FSCUE5dQyC9sOihc0P-yrelEMEtH/view?usp=sharing
1. Put on a GCS filesystem
1. Open the file:

```
import gcsfs
import pandas as pd
fs = gcsfs.GCSFileSystem()
filepath_or_buffer = fs.open("gs://your/bucket/weird.tsv", "r")
gcsfs_ = pd.read_csv(filepath_or_buffer, sep="\t", header=None)
gcsfs_.shape
```

Returns

```
(3408, 32)
```

Now, if you read with the tensorflow api:

```
from tensorflow.python.lib.io import file_io
with file_io.FileIO("gs://your/bucket/weird.tsv", "r") as f:
    df = pd.read_csv(f, sep="\t", header=None)
    df.shape
```

The shape is correct:

```
(2869, 32)
```

It's also correct if you open the file from your local filesystem. I even did a character count, and the file read through gcsfs returns a wrong number of `\n` characters. 

I can post more details here, if needed.

Versions:
```
In [2]: import sys

In [3]: sys.version
Out[3]: '3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) \n[GCC 7.3.0]'

In [4]: import gcsfs

In [5]: gcsfs.__version__
Out[5]: '0.3.0'

In [6]: import pandas as pd
p
In [7]: pd.__version__
Out[7]: '0.25.0'

In [8]: import tensorflow as tf
tf._
In [9]: tf.__version__
Out[9]: '1.12.0'

In [10]: sys.platform
Out[10]: 'linux'

In [11]: import platform

In [12]: platform.platform()
Out[12]: 'Linux-4.9.0-8-amd64-x86_64-with-debian-9.9'

```

**Comment by martindurant** [comment]
Please try with fsspec most recent release or with master?

**Comment by martindurant** [comment]
Please wait for the fix to be merged, and the following release of fsspec...
