### ISSUE TITLE
Large objects in serialized FileSystem

### ISSUE THREAD

**Issue by TomAugspurger** [dask/gcsfs#181]
Not sure what yet

```python
import gcsfs
import pickle

fs = gcsfs.GCSFileSystem(token="anon")
print(len(pickle.dumps(fs)))
files = fs.glob('anaconda-flights/data.parquet/data.parquet/part*')
print(len(pickle.dumps(fs)))
```

That outputs

```
2598
7132903
```

for me.

Looking into the cause.

**Comment by TomAugspurger** [comment]
It's `GCSFS._listing_cache`. I don't think that should necessarily be pickled.

**Comment by martindurant** [comment]
Certainly should be dropped. Other things like `.dircache` are already dropped (in AbstractFileSystem)

**Comment by TomAugspurger** [comment]
Will do a PR quick.
