### ISSUE TITLE
Performance regression in 0.3.0

### ISSUE THREAD

**Issue by bnaul** [dask/gcsfs#186]
When opening a file in a bucket with a lot of files (500k in my case), I see a huge decrease in performance between 0.2.3 and 0.3.0 through master.

Before:
```
[nav] In [1]: import gcsfs
         ...: fs = gcsfs.GCSFileSystem()
         ...: %time fs.open('gs://<bucket>/89257551a5d8c84ba07c42c6af490010.txt').read()
CPU times: user 2.98 ms, sys: 1.18 ms, total: 4.16 ms
Wall time: 63.8 ms
```
Now:
```
[nav] In [1]: import gcsfs
         ...: fs = gcsfs.GCSFileSystem()
         ...: %time fs.open('gs://<bucket>/89257551a5d8c84ba07c42c6af490010.txt').read()
CPU times: user 11.9 s, sys: 4.19 s, total: 16.1 s
Wall time: 2min 55s
```

I don't see this behavior for the same file in a nearly empty bucket, so I'm relatively sure it has something to do with the number of files.

3 minutes is roughly how long it took me to `gsutil ls | wc` the bucket, maybe there's an inadvertent list of all files going on...?

**Comment by TomAugspurger** [comment]
It does look like a `info` is called https://github.com/intake/filesystem_spec/blob/e6b7e1c6b85553f0f4df17f8a8ea8ee049de1f5a/fsspec/spec.py#L871-L877. The spec docstring says


> The default implementation should calls ls and could be overridden by a
> shortcut. kwargs are passed on to ```ls()``.

@martindurant would / could gcsfs implement a faster `info`? Does s3fs need the same?

**Comment by martindurant** [comment]
s3fs does this already, a HEAD request in `info()`, if the parent directory does not already exist in the cache.

**Comment by TomAugspurger** [comment]
Sounds good. @bnaul would you be willing / able to make a PR? Otherwise I
can try to make one by the end of the week.
