### ISSUE TITLE
Avoid downloading list of files in bucket when object path contains no wildcard

### ISSUE THREAD

**Issue by halfdanrump** [dask/gcsfs#21]
Original discussion [here](https://github.com/dask/dask/issues/2746)

Quick summary: When reading a single file from a bucket containing a very large number of files, the read time can be very long before gcsfs downloads the list of all the files in the bucket. For a bucket with over 4 million files, this can take up to 15 minutes. 

Suggested fix (easy): Check if the object path contains a wildcard. If it does not, then just download file. If it does, then proceed to download list of files. 

Suggested fix (hard, not sure how to do yet, suggested by @martindurant ): implement prefix/delimiter listing, i.e., make it possible to use wildcard in object path (.e.g., `bag.read_text('gs://mybucket/2017/01/*.csv')`) *without* having to download list of files from entire bucket.

**Comment by martindurant** [comment]
Fixed by ef42a5360ca577ddacac312a1e44ad7520dba2c1
