### ISSUE TITLE
Service Unavailable is not retried

### ISSUE THREAD

**Issue by JacobHayes** [dask/gcsfs#221]
Fairly rarely when reading a file (maybe tens out of tens of thousands), I get a `RuntimeError("b'Service Unavailable'")` from `validate_response`. I'm not sure of the status code, but seems like it is a retriable error - it pops up in a dask cluster w/ hundreds of workers but doesn't affect other workers or later requests on the same worker.

I know this is affecting some reads, but I suspect it might also be affecting some of our writes resulting in invalid files - we open the file to write and catch exceptions within the context to track fail/pass without re-raising. I'm guessing that one chunk is flushed while another is not (but could have been retried).

As far as I can tell, it should just need an extra check in [`core.validate_response`](https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L151) and an update to [`is_retriable`](https://github.com/dask/gcsfs/blob/master/gcsfs/utils.py#L41) or `RETRIABLE_EXCEPTIONS`.

I'll try to reproduce the issue w/ a debugger to inspect the status code, but I guess we could just check the content and raise a retriable error accordingly. Here's a trace for a write from our logs:
<img width="1076" alt="service-unavailable" src="https://user-images.githubusercontent.com/2555532/70369015-cb50f500-1867-11ea-96a1-1250b791baf7.png">

Has anyone else seen this or similar issues?

**Comment by TomAugspurger** [comment]
I haven't seen that, but that exception does seem to be retryable.

Do you know who exactly is giving that text "Service Unavailable"? That's the response body from some request?

**Comment by martindurant** [comment]
It does sounds very reasonable that "service unavailable" should be a retriable error, so indeed, all we need to know are the details of exactly what that response looks like, so we can recognise it.

**Comment by JacobHayes** [comment]
I'll try to recreate it with some more thorough logs injected today on status code, the url, etc. The "Service Unavailable" text is from [`r.content`](https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L161), which is then raised as a `RuntimeError`

**Comment by JacobHayes** [comment]
Assuming #226 handles this
