### ISSUE TITLE
Support default credentials

### ISSUE THREAD

**Issue by jean-philippe-martin** [dask/gcsfs#23]
It'd be nice to be able to use this library just using gcloud's default credentials, instead of having to juggle files.

**Comment by martindurant** [comment]
Do you know how "default credentials" are defined or stored by gcloud?

**Comment by jean-philippe-martin** [comment]
My understanding is that they're retrieved like this:

```
credentials = GoogleCredentials.get_application_default()
```

All I know is what's in [this documentation page](https://developers.google.com/identity/protocols/application-default-credentials). It's awfully convenient to be able to log in via gcloud and then all the applications work, which is why I'm suggesting the feature.

**Comment by martindurant** [comment]
I bet it doesn't say anywhere how that's actually achieved... I don't want gcsfs to have to depend upon gcloud-client if I can possibly avoid it. By the name of the method, it's probably just loading `~/.config/gcloud/application_default_credentials.json`, but it'd be nice to know how consistent that location is across platforms.

**Comment by jean-philippe-martin** [comment]
Are you sure this requires gcloud-client? From the documentation it looks like `GoogleCredentials` is in `oauth2client`, which gcfs already depends on (the [oauth2client docs](http://oauth2client.readthedocs.io/en/latest/source/oauth2client.client.html#oauth2client.client.GoogleCredentials) seem to agree). 
This may be an easy fix.

**Comment by martindurant** [comment]
You are right - but the format is not quite the same as in the file; the following works:
```python
au = oauth2client.client.GoogleCredentials.get_application_default()
tok = {"client_id": au.client_id, "client_secret": au.client_secret, "refresh_token": au.refresh_token, "type": "authorized_user"}
gcs = gcsfs.GCSFileSystem(project='myproject', token=tok)
```
