### ISSUE TITLE
gcsfs can't access google storage file, switches to anon user

### ISSUE THREAD

**Issue by kapilkd13** [dask/gcsfs#231]
I am trying to read a csv file present in gs bucket directly into dataframe. 
I used `gcloud auth login` to authorize account. But when I try to use gcsfs it thorws:
`gcsfs.utils.HttpError: Anonymous caller does not have storage.objects.list access to <my-bucket>`

Now I ca list/download my files using `gsutil`. I can also list these files by passing `adc` file as token to `fs=gcsfs.GCSFileSystem(token='adc.json')`. My issue is how do I set it as default. Is there a particular location where I put this file. I couldn't find anything in docs.

**Comment by kapilkd13** [comment]
Update: This works with version 0.5.0. Might be an issue with current release.

**Comment by TomAugspurger** [comment]
What's the output of `gcsfs.__version__`? Can you post your code and the traceback? How are you authenticating?

**Comment by kapilkd13** [comment]
gcsfs version is 0.6.0
I am working on a google colab notebook, authenticating it with `gcloud auth login` so to access gcv bucket created in my account.  I also tried uploading application credentials(adc.json) and exporting with `export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"` but both failed similarly.
Here is a minimal code example,
```
import pandas
import gcsfs
```
authenticating with auth login
```
!gcloud auth login
>>> You are now logged in as [kapil.kumar@dxxxxt.in].
df=pd.read_csv("gs://<bucket file path>")
>>> /usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _list_objects(self, path)
    640             return clisting
    641 
--> 642         listing = self._do_list_objects(path)
    643         retrieved_time = time.time()
    644 

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-128> in _do_list_objects(self, path, max_results)

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     50         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     51 
---> 52     return f(self, *args, **kwargs)
     53 
     54 

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _do_list_objects(self, path, max_results)
    661             delimiter="/",
    662             prefix=prefix,
--> 663             maxResults=max_results,
    664         ).json()
    665 

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-124> in _call(self, method, path, *args, **kwargs)

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     50         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     51 
---> 52     return f(self, *args, **kwargs)
     53 
     54 

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    556                     continue
    557                 logger.exception("_call non-retriable exception: %s", e)
--> 558                 raise e
    559 
    560         return r

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    534                     timeout=self.requests_timeout,
    535                 )
--> 536                 validate_response(r, path)
    537                 break
    538             except (

/usr/local/lib/python3.6/dist-packages/gcsfs/core.py in validate_response(r, path)
    179             raise ValueError("Bad Request: %s\n%s" % (path, msg))
    180         elif error:
--> 181             raise HttpError(error)
    182         else:
    183             raise RuntimeError(m)

HttpError: Anonymous caller does not have storage.objects.list access to kapil_bert.

```
It looks like gcsfs can't recognize/authenticate logged in user and switching to `anonymous` user, causing access denied error.
As mentioned above this worked with version 0.5.0

**Comment by TomAugspurger** [comment]
You should be explicit about what type of authentication you're using. So to debug this use `GCSFileSystem(token=...)`.

You can also try bisecting the commits between 0.5 and 0.6 to see where things changed.

**Comment by kapilkd13** [comment]
@TomAugspurger  Using `GCSFileSystem(token=...)` and specifying token explicitly, I am able to list/access gcv bucket files. My issue is `GCSFileSystem` should access `gcloud credentials` by default as mentioned in docs [here](https://gcsfs.readthedocs.io/en/latest/api.html). Also I don't know a way to pass token to `pandas read_csv` which I am using to read files directly. I want to avoid 
```
import pandas as pd
import gcsfs

fs = gcsfs.GCSFileSystem(token='.....' ,project='my-project')
with fs.open('bucket/path.csv') as f:
    df = pd.read_csv(f)
```

I won't be able to debug it for specific commit as I got it working with version `0.5.0` . You may close this issue if you want.

**Comment by TomAugspurger** [comment]
If there's a bug on master we should leave the issue open.

You might also confirm that the default project is set correctly. Older
versions of gcsfs would silently change the project on you with certain
auth methods. I don't recall when that was fixed.

> Also I don't know a way to pass token to pandas read_csv which I am using
to read files directly.

I believe there's an open pandas issue for that, if you're interested in
working on it.

**Comment by martindurant** [comment]
Where is the json file you are providing to `token=`? `gcloud login` should have made a default application credentials file, which for me lives in ".config/gcloud/". 

Please check the value of `fs.method` to see what connection method was attempted. If this is "google_default", then please see the output of `google.auth.default()` to see what google thinks your login actually is.

**Comment by LienM** [comment]
Jumping on this thread: I have the same issue with gcsfs 0.6.0, even when I pass in valid credentials:
`fs = gcsfs.GCSFileSystem(project='project-id', token="/Users/<user>/.config/gcloud/application_default_credentials.json") `
Attempting to run fs.ls, fs.find, all of them give the above HTTPError. 
When I call fs.method it says 'anon'. 

The weirdest thing about it is that if I don't try to use gcsfs directly, but instead read any file from the same bucket using `dd.read_parquet(<gcs url>)` it works fine, even though I assume it uses the same underlying functionality? 

When I downgrade to 0.5.0 I get a different error `RefreshError: ('invalid_scope: Bad Request', '{\n  "error": "invalid_scope",\n  "error_description": "Bad Request"\n}')`. Still debugging why that is the case.

**Comment by martindurant** [comment]
`dd.read_parquet` passes the contents of the `storage_options` kwargs (a dict) to the gcsfs constructor, so will be the equivalent of `GCSFileSystem()` if you don't specify anything.

**Comment by Gabsha** [comment]
See [here](https://github.com/googleapis/google-auth-library-python/blob/46fa9c4fa4783ef584b132e0628dc6031a7e48b5/google/auth/_default.py#L222) for how google.auth tries to read your credentials. Enabling application-default worked for me: `gcloud auth application-default login`

**Comment by vlasenkoalexey** [comment]
#255 should fix this issue.

Following code now works just fine:
```python
from gcsfs.core import GCSFileSystem
gcs = GCSFileSystem('<project_id>', token='/Users/<username>/.config/gcloud/application_default_credentials.json')
gcs.ls('<bucket>') 
```

FYI, to use default GCP authentication fallback mechanism you can use following:
```python
from gcsfs.core import GCSFileSystem
import google.auth

credentials, _ =google.auth.default()
gcs = GCSFileSystem('<project_id>', token=credentials)
gcs.ls('<bucket>') 
```

**Comment by jms-dipadua** [comment]
FWIW, I've been ramming my head against this one for the last day.

Using gcsfs (0.6.2) through Pandas, I was able to open files without a problem.  When I used Docker, the container was no longer able to access gs:// buckets -- I was receiving the same error above: ```csfs.utils.HttpError: Anonymous caller``` 

I thought trying @vlasenkoalexey approach to getting the default credentials may help. His suggestion does allow for directly authenticating and mounting the filesystem, which was failing outside Pandas even when I provided a credential file (as @LienM mentioned). Despite working locally, his google.auth.default() to mount fails to authenticate within the docker container. 

I'm not sure my issue is related but thought I would mention it on the chance it is.

**Comment by elannert** [comment]
I had this same issue. It runs in a docker container by creating a new service account, generating a key, giving it objectViewer on the bucket, and setting this before running:

export GOOGLE_APPLICATION_CREDENTIALS="sa-key.json"

note - i did not need to use the 
import google.auth
credentials, _ =google.auth.default()

I tried other methods of using the user I was authenticated as and using the default service account of the container which both generated the anon problem.

**Comment by davidxia** [comment]
Does this library use the `GOOGLE_APPLICATION_CREDENTIALS` env var? I set that value to the path of my `application_default_credentials.json` and have `GCSFileSystem(project=MY_PROJECT)`, but I get the error `gcsfs.retry.HttpError: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object., 401`.

`GCSFileSystem(project=MY_PROJECT, token=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))` works which makes me suspect this library doesn't respect `GOOGLE_APPLICATION_CREDENTIALS`.

I'm using the latest gcsfs 2022.8.2.

**Comment by martindurant** [comment]
@sl2902 , please start a new issue so we can discuss
