### ISSUE TITLE
TypeError on commit

### ISSUE THREAD

**Issue by remram44** [dask/gcsfs#237]
It seems that `_upload_chunk()` does not check if `self.offset` has been set.

```
Traceback (most recent call last):
    ...
  File "/usr/local/lib/python3.7/site-packages/gcsfs/core.py", line 1216, in commit
    self._upload_chunk(final=True)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-18>", line 2, in _upload_chunk
  File "/usr/local/lib/python3.7/site-packages/gcsfs/core.py", line 52, in _tracemethod
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gcsfs/core.py", line 1166, in _upload_chunk
    self.offset + l - 1,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
I suppose this happens if the file is small enough so that the final chunk is the first one, and autocommit=False. gcsfs 0.6.0

**Comment by martindurant** [comment]
I believe this is fixed in master

**Comment by remram44** [comment]
Do you mean fsspec master, not gcsfs master?

**Comment by remram44** [comment]
I managed to avoid this exception by calling `flush(force=True)` before `commit()`, but then no file gets created :open_mouth:

**Comment by martindurant** [comment]
> Do you mean fsspec master, not gcsfs master?

I believe the latter, but perhaps try with both?

**Comment by remram44** [comment]
Thanks for the pointer! I have tried with current masters, unfortunately I get the same traceback:

```
...
    self.offset + l - 1,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by martindurant** [comment]
Can you show exactly what you did? The following works
```
In [15]: with gcs.open('mdtemp/output', 'wb') as f:
    ...:     f.write(b'small data')
    ...:

In [16]: gcs.cat('mdtemp/output')
Out[16]: b'small data'
```

**Comment by remram44** [comment]
I'm using `autocommit=False`

Minimum test case:

```python
from base64 import b64decode
import json
import os
import gcsfs


fs = gcsfs.GCSFileSystem(
    project=os.environ['GCS_PROJECT'],
    token=json.loads(b64decode(os.environ['GCS_CREDS'])),
)

with fs.open('datamart-dev-datasets/test-upload', 'wb') as fp:
    fp.write(b'12345')
    fp.flush(force=True)  # exception without this
    fp.commit()

# No file has been created in the bucket
```

**Comment by martindurant** [comment]
How about
```

with fs.open('datamart-dev-datasets/test-upload', 'wb', autocommit=False) as fp:
    fp.write(b'12345')

fp.commit()
```
?

**Comment by remram44** [comment]
I think I had issues running it in this order with `s3fs`. Anyway, same result with `gcsfs`, no file created.

**Comment by martindurant** [comment]
Looks like this will take a little digging, your help appreciated. There should be such a test in the gcsfs and f3fs suites. Note that expected usage would be more like:

```
In [24]: fs.transaction.start()

In [25]: with fs.open('mdtemp/test-upload', 'wb') as fp:
    ...:     fp.write(b'12345')
    ...:

In [26]: fs.transaction.complete()
```
or
```
In [29]: with fs.transaction:
    ...:     with fs.open('mdtemp/test-upload', 'wb') as fp:
    ...:         fp.write(b'12345')
```
(but still doesn't work)

**Comment by martindurant** [comment]
Seems to work for s3fs

**Comment by martindurant** [comment]
The following appears to fix it. Would appreciate it you would make the change and a test for it, and submit a PR. I would get around to this too eventually, but it may take some time.

```diff
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -1168,7 +1168,7 @@ class GCSFile(fsspec.spec.AbstractBufferedFile):
         else:
             if l < GCS_MIN_BLOCK_SIZE:
                 if not self.autocommit:
-                    return
+                    return False
                 elif not final:
                     raise ValueError("Non-final chunk write below min size.")
             head["Content-Range"] = "bytes %i-%i/*" % (self.offset, self.offset + l - 1)
```

**Comment by remram44** [comment]
Of course! Much appreciated. Will test ASAP.

Your lib is saving me much headache dealing with all the cloud APIs. I'd debug this myself but the back-and-forth between gcsfs and fsspec has me a little confused.

**Comment by remram44** [comment]
The patch makes this work with close-commit! Commit-close still raises the TypeError, flush-commit-close also works.

**Comment by martindurant** [comment]
`commit()` on a file that has not yet been closed should be an error - but a better-explained one
