### ISSUE TITLE
.info now requires storage.object.get

### ISSUE THREAD

**Issue by JacobHayes** [dask/gcsfs#245]
After https://github.com/dask/gcsfs/pull/242, calling `.info` without the file cached downloads the object instead of just pulling metadata. However, the [GCP permissions](https://cloud.google.com/storage/docs/access-control/iam-permissions) allow one to get object metadata (and crucially for us, the file checksum) with only `storage.objects.list`. We were relying on the old behavior/standard GCS IAMs to support developers who don't have access to file _contents_ to still be able to track changes and dependencies.

How important is it to download the object on `.info` calls? It seems fair enough to use a cache read to avoid an API call for `.info`, but populating the cache turns `.info` into a much more expensive call (both in permissions and potentially storage+time) and doesn't mean a download is actually used (in fact, we call .info *very* often on transient instances that never need file contents, which would ideally be kept very fast). If it's worth keeping `_get_object` in `.info`, then perhaps we need to expand on [this error handling](https://github.com/dask/gcsfs/blob/70f5581443e2a8da846a8ce0c5fd474e87cf8eb4/gcsfs/core.py#L724) to catch permission issues. Any other thoughts or ideas?

**Comment by martindurant** [comment]
Another example of different users having different needs :|

Can you tell explicitly from the error that your situation has been hit?

**Comment by JacobHayes** [comment]
> Another example of different users having different needs :|

Definitely! I was trying to figure out what prompted that specific change to get a feel for the need/use case, but didn't find it/dig too hard.

> Can you tell explicitly from the error that your situation has been hit?

I'm not quite sure I know what you mean, but yes, the error message is quite clear:
```
----> 1 import gcsfs; gcsfs.GCSFileSystem().info("gs://<redacted>")
~/model/.venv/lib/python3.7/site-packages/gcsfs/core.py in info(self, path, **kwargs)
    721         # Check exact file path
    722         try:
--> 723             return self._get_object(path)
    724         except FileNotFoundError:
    725             pass
~/model/.venv/lib/python3.7/site-packages/gcsfs/core.py in _get_object(self, path)
    530 
    531         result = self._process_object(
--> 532             bucket, self._call("GET", "b/{}/o/{}", bucket, key).json()
    533         )
    534 
~/model/.venv/lib/python3.7/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    468                     timeout=self.requests_timeout,
    469                 )
--> 470                 validate_response(r, path)
    471                 break
    472             except (HttpError, RequestException, GoogleAuthError) as e:
~/model/.venv/lib/python3.7/site-packages/gcsfs/core.py in validate_response(r, path)
    112             raise FileNotFoundError
    113         elif r.status_code == 403:
--> 114             raise IOError("Forbidden: %s\n%s" % (path, msg))
    115         elif r.status_code == 502:
    116             raise ProxyError()
OSError: Forbidden: https://www.googleapis.com/storage/v1/b/<redacted>
<redacted>@<redacted>.com does not have storage.objects.get access to <redacted>.
```
The user in that example had `storage.objects.list` permission but not `storage.objects.get` for the object. Even knowing the exact error though, we can't work around it outside `gcsfs` unless we just fallback to always using `.ls(...)[0]` instead of `.info(...)`,

**Comment by martindurant** [comment]
Yep, understood. The presence of "storage.objects.get" makes this detectable (although, of course, this doesn't imply you do have list permission). It is odd that it should be forbidden, since the request is actually only for the HEAD of the object, the same metadata as from listing.
If you list first, the error is avoided?

**Comment by JacobHayes** [comment]
Oops, `.ls` also fails with the same error. I must've tested that after downgrading to https://github.com/dask/gcsfs/commit/ab1d97d368c6b1e168e7d64752f831680786bf87. 😅

Should be fully reproducible with this:
```
# I ran the below to set things up:
#     gcloud config set project jacob-hayes
#     gcloud iam roles create storageListRole \
#         --project=jacob-hayes \
#         --title 'Storage List' \
#         --permissions 'storage.buckets.get,storage.buckets.list,storage.objects.list'
#     gsutil mb -b on gs://gcsfs-245
#     gsutil iam ch allUsers:"projects/jacob-hayes/roles/storageListRole" 'gs://gcsfs-245/'
#     echo "example" | gsutil cp - "gs://gcsfs-245/allUsers-object-list"

# Works
pip3 install --upgrade git+https://github.com/dask/gcsfs.git@ab1d97d368c6b1e168e7d64752f831680786bf87#egg=gcsfs
python3 -c 'import gcsfs; print(gcsfs.GCSFileSystem(token="anon").ls("gs://gcsfs-245/allUsers-object-list", detail=True)[0])'
python3 -c 'import gcsfs; print(gcsfs.GCSFileSystem(token="anon").info("gs://gcsfs-245/allUsers-object-list"))'

# Errors
pip3 install --upgrade git+https://github.com/dask/gcsfs.git@2182133c7848c82e18c802f91914af7faf1909e1#egg=gcsfs
python3 -c 'import gcsfs; print(gcsfs.GCSFileSystem(token="anon").ls("gs://gcsfs-245/allUsers-object-list", detail=True)[0])'
python3 -c 'import gcsfs; print(gcsfs.GCSFileSystem(token="anon").info("gs://gcsfs-245/allUsers-object-list"))'
```

**Comment by martindurant** [comment]
Can you debug to see exactly what call is being made, how it's different?

Can you try without the "gs://"?

I must admit that it never occurred that people might want to list files without accessing them.

**Comment by JacobHayes** [comment]
Sure, I might be able to take a look tonight.

Same errors without `gs://`.

Yes, it's probably a bit of an odd use case, but we're using it to track dependencies and determine what things are out of date and need rebuilt. Fairly often we check things locally with metadata only access to sensitive files and submit rebuild jobs as needed.

**Comment by martindurant** [comment]
So does listing the directory with `ls` work currently? `info()` (and `exists`, etc.) should be checking for a previous listing containing the file in question before attempting a get_object.
