### ISSUE TITLE
gcsfs==0.6.1 can't be used with petastorm

### ISSUE THREAD

**Issue by vlasenkoalexey** [dask/gcsfs#254]
It fails because norm_path was removed in 
https://github.com/dask/gcsfs/commit/2182133c7848c82e18c802f91914af7faf1909e1#diff-64baa9177ba98eff7c6d16d3ae6b2bf1
and petastorm uses this method.
Need to add it back.

**Comment by martindurant** [comment]
A reappearance of `norm_path` would be fine, but of course, it may be better to update the dependency. Sorry for breaking petastorm!
