### ISSUE TITLE
Releasing gcsfs 0.6.2 to pypi

### ISSUE THREAD

**Issue by vlasenkoalexey** [dask/gcsfs#258]
The main goal of 0.6.2 release is to unblock petastorm usage #254 

Currently gcsfs fails non deterministically on petastorm: https://github.com/uber/petastorm/issues/547

petastorm can only use 0.6.0, and that version has issue with retry logic fixed in 0.6.1 by #226 

I can do release myself if you give me gcsfs project access on pypi.
My username on pypi is vlasenkoalexey

**Comment by martindurant** [comment]
Let's merge #257 , and then I can do it.

**Comment by vlasenkoalexey** [comment]
Let's merge #257 first.
Thanks for quick response and for doing release!!!

**Comment by martindurant** [comment]
On pypi now

**Comment by vlasenkoalexey** [comment]
Thanks!!!
