### ISSUE TITLE
service_account not accepted for token

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#26]
Google returns `ValueError: Only 'authorized_user' tokens accepted, got: service_account`. Limitation or can that be extended ?

Note: @martindurant this is yet another great lib !! G only implemented `cloudstorage` for their GAE Standard. File-like objects are perfect to minimize memory usage and skip the need for disk.

**Comment by martindurant** [comment]
What did you do to get the error, above? 

I believe this is happening directly within gcsfs - GCS needs to authenticate using a specific user rather than a service. I don't know if using service account credentials directly is possible or what change would need to be made.

**Comment by yiga2** [comment]
` File "xx\core.py", line 217, in connect
    token = self._parse_gtoken(token)`
`File "xx\core.py", line 188, in _parse_gtoken
    % typ)`
`ValueError: Only 'authorized_user' tokens accepted, got: service_account`

No worries, I just created a user token and works fine.

**Comment by yiga2** [comment]
I let you close if you feel this doesn't justify for an enhancement. I have no use case to work with service-account only.

**Comment by martindurant** [comment]
I will close rather because I don't know how to use those tokens :)
