### ISSUE TITLE
Retry after encountering a checksum failure in GCSFileSystem.cat?

### ISSUE THREAD

**Issue by spencerkclark** [dask/gcsfs#267]
We've been using gcsfs fairly heavily for loading data from zarr stores in the cloud; in general it has worked really well.  A basic pattern might look something like this:

```python
import gcsfs
import xarray

PROJECT = "example-project"
STORE = "gs://path-to-store/store.zarr"

gcs = gcsfs.GCSFileSystem(project=PROJECT)
mapper = gcs.get_mapper(STORE)
ds = xarray.open_zarr(mapper)
result = ds.mean().compute()
```

Every now and then -- I honestly don't know what dictates it -- there are days when we encounter transient errors like this when performing the computation:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)

... (very long traceback)

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py in cat(self, path)
    888                 if key == "md5":
    889                     md = b64decode(val)
--> 890                     assert md5(r.content).digest() == md, "Checksum failure"
    891         return r.content
    892 
AssertionError: Checksum failure
```

Typically one can retry the script a few times and eventually the full computation succeeds.  This can be a bit frustrating, however, because particularly for long-running computations, many downloads will be performed before one of these errors is hit, and re-running the script means starting over from scratch.  Would it be appropriate to add some logic to `GCSFileSystem.cat` that would retry a download if a checksum failure occurred?  I believe there are other places in gcsfs where retry logic is used to work around these kinds of transient issues.

Apologies for not being able to provide a minimal working example -- the transient nature of the issue makes that difficult.  

cc: @nbren12 @oliverwm1 @brianhenn

**Comment by martindurant** [comment]
Are you able to determine if, for these cases, the downloaded data really is wrong, perhaps truncated? It would be interesting to see if the http response headers claim partial data.

Not opposed to retry on checksum failure.

On July 10, 2020 6:27:02 PM EDT, Spencer Clark <notifications@github.com> wrote:
>We've been using gcsfs fairly heavily for loading data from zarr stores
>in the cloud; in general it has worked really well.  A basic pattern
>might look something like this:
>
>```python
>import gcsfs
>import xarray
>
>PROJECT = "example-project"
>STORE = "gs://path-to-store/store.zarr"
>
>gcs = gcsfs.GCSFileSystem(project=PROJECT)
>mapper = gcs.get_mapper(STORE)
>ds = xarray.open_zarr(mapper)
>result = ds.mean().compute()
>```
>
>Every now and then -- I honestly don't know what dictates it -- there
>are days when we encounter transient errors like this when performing
>the computation:
>
>```
>---------------------------------------------------------------------------
>AssertionError                            Traceback (most recent call
>last)
>
>... (very long traceback)
>
>~/miniconda3/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py in
>cat(self, path)
>    888                 if key == "md5":
>    889                     md = b64decode(val)
>--> 890                     assert md5(r.content).digest() == md,
>"Checksum failure"
>    891         return r.content
>    892 
>AssertionError: Checksum failure
>```
>
>Typically one can retry the script a few times and eventually the full
>computation succeeds.  This can be a bit frustrating, however, because
>particularly for long-running computations, many downloads will be
>performed before one of these errors is hit, and re-running the script
>means starting over from scratch.  Would it be appropriate to add some
>logic to `GCSFileSystem.cat` that would retry a download if a checksum
>failure occurred?  I believe there are other places in gcsfs where
>retry logic is used to work around these kinds of transient issues.
>
>Apologies for not being able to provide a minimal working example --
>the transient nature of the issue makes that difficult.  
>
>cc: @nbren12 @oliverwm1 @brianhenn
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/gcsfs/issues/267

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrocklin** [comment]
Also +1 on retry by default

**Comment by spencerkclark** [comment]
> Are you able to determine if, for these cases, the downloaded data really is wrong, perhaps truncated? It would be interesting to see if the http response headers claim partial data.

Thanks @martindurant -- what is the best way to do that?  We have not looked into something like that when encountering this issue before, but we can try when we encounter it again.  How would it change how we address it?

**Comment by martindurant** [comment]
I am in the middle of an extensive refactor to add async to gcsfs. I would advise waiting a little until that it done.
Afterwards, perhaps it would be best to factor out the retry and apply it not just in _call, but any of the requests that might be expected to fail sometimes.

**Comment by nbren12** [comment]
Oh that's exciting! I think async will be worth the wait on this issue.

**Comment by martindurant** [comment]
https://github.com/dask/gcsfs/pull/268

**Comment by spencerkclark** [comment]
All sounds good @martindurant -- thanks!

**Comment by martindurant** [comment]
Async PR is in. 
Would someone here want to have a go at retrying after checksum failures? I would like to have a go at async for s3fs first...

**Comment by spencerkclark** [comment]
> I would like to have a go at async for s3fs first...

Sure!  We're not in a rush here.  Fortunately this particular transient error isn't too frequent.

**Comment by spencerkclark** [comment]
> Would someone here want to have a go at retrying after checksum failures?

For sure!  I can look into it over the next week or so.  We're not in a particular rush here, as fortunately this transient error is not too frequent.
