### ISSUE TITLE
cache block to reuse by readline

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#27]
I have a file of 30M lines and know that each line is max 2000 bytes long. 
So if I want to iterate through the "file" (blob), I can specify the length of bytes to fetch to limit waste but doing that 3M times would cost huge latency. 

I wonder if it would not be better - through an option - to read and cache a full block and read the lines from there. 

This can be done outside of GCSFS but thought it may be embedded.

**Comment by martindurant** [comment]
Are you sure this isn't already the functionality?

Note that GCSFile.readline() is really just seeking for `b'\n'`, and wrapping your file object in `io.TextIOWrapper` is a totally reasonable and complete solution. I agree in principle that if the open mode were `'rt`', we could do this automatically for the user.

**Comment by yiga2** [comment]
My bad - hadn't tested it but then I wonder why specifying the length if a block is in memory. Anyways, will test and report if applicable.

A side note on walk() method and a few others not being documented

**Comment by yiga2** [comment]
tested successfully with different block sizes
