### ISSUE TITLE
DOC: example of reading a parquet file

### ISSUE THREAD

**Issue by raybellwaves** [dask/gcsfs#274]
I'm not sure if this should live in gcsfs. I understand gcsfs is a framework for reading data from gcloud using python. However, I think it may still be beneficial to add a copy-paste example in the docs and make a note that is uses dask.dataframe (i.e. you should have dask installed0.

i.e. towards the end of https://gcsfs.readthedocs.io/en/latest/#examples you can add:

Reading a parquet files using `dask.dataframe`:

```
ddf = dd.read_parquet("gs://dask-nyc-taxi/yellowtrip.parquet", storage_options={"token": "anon"})
```

**Comment by martindurant** [comment]
I copied the s3fs example to look like [this](https://gcsfs.readthedocs.io/en/latest/#integration) - is that good enough?

**Comment by raybellwaves** [comment]
Yes. Not sure how I missed that first time round. I like the use of `pd.read_excel`. Now I may see if it well documented in pandas...

**Comment by martindurant** [comment]
(it is not yet released in pandas, or even merged, but coming soon! Of course, gcsfs hasn't had its next release yet either)

**Comment by martindurant** [comment]
https://github.com/pandas-dev/pandas/pull/35655/files#diff-db9d1fb225a44f3c818e08de7b9cb641
