### ISSUE TITLE
TypeError: copy() got an unexpected keyword argument 'recursive'

### ISSUE THREAD

**Issue by frankShih** [dask/gcsfs#275]
**What happened**:
I try to add "gcsfs==0.4.0" in my GCP cloud function and deploy it.
Then the error occurs.
>TypeError: copy() got an unexpected keyword argument 'recursive'

**Minimal Complete Verifiable Example**:
I create a clear python environment, install `gcsfs==0.4.0` .
And run the code below:
```python
# Put your MCVE code here
import gcsfs
fs = gcsfs.GCSFileSystem(project=proj_name)
fs.invalidate_cache()
fs.mv(source_path, target_path)
```
Which shows the error as I mentioned above.

**Anything else we need to know?**:
I try to trace it down, and found that if I use "gcsfs==0.4.0 & fsspec==0.6.2",  everything works fine.
Does that mean 0.4.0 is deprecated and I should use the latest version (`gcsfs==0.6.2` or other stable versions)?

>PS. when I use `pip install gcsfs==0.4.0`, it default installs fsspec-0.8.0

**Environment**:

- Dask version: 
- Python version: 
3.7.7
- Operating System: 
M$ Win10
- Install method (conda, pip, source): 
`conda` create python env & `pip` install gcsfs

**Comment by martindurant** [comment]
Unfortunately, the release of fspec is slightly ahead of gcsfs. You could downgrade fsspec or use gcsfs master. A release should come within the week.
For the future, it may be worth my while to require exact version deps for release, not just the minimum versions as listed right now.
