### ISSUE TITLE
Recursive remove fails

### ISSUE THREAD

**Issue by pvanderlinden** [dask/gcsfs#279]
While google cloud storage never really supported directories. I always had issues with "directories" sticking around on google cloud storage when it was created with pyspark, and deleted with gcsfs. These were empty "directories", which technically should not be possible with google cloud storage, but they were real (gsutil saw those empty directories as well). 

Since 0.7.0 gcsfs fails on deleting "directories", is this something which is fixed in gcsfs?

**Comment by martindurant** [comment]
> Since 0.7.0 gcsfs fails on deleting "directories", is this something which is fixed in gcsfs?

Apparently not?
I am thinking to change the behaviour of `find` to only use prefix and not delimiter, which would solve this issue ( #273 )

**Comment by pvanderlinden** [comment]
I'm testing my fix now with 0.7.0, but now rm(path, recursive=True), crashes.

**Comment by pvanderlinden** [comment]
From 0.7.0 recursive remove will crash with `No such object` @martindurant

**Comment by martindurant** [comment]
Also possibly related https://github.com/intake/filesystem_spec/issues/378

**Comment by pvanderlinden** [comment]
I think it's a combination, you used to be able to remove "directories", which the recursive implementation will do as well. Which then raises an exception.

**Comment by martindurant** [comment]
> No such object

Seems we are returning both keys and implied directories - maybe "/" characters are getting. lost in the wash

**Comment by pvanderlinden** [comment]
Looks like it, although removing implied directories did something in 0.6.x, and if I didn't remove these implied directories, they were also visible after the recursive remove with first party tools like gsutil. I have never understood what those were those, and only pyspark was able to create those empty directories.

**Comment by martindurant** [comment]
They are empty (zero-size) keys, with names that happen to be the same as the prefix of other keys. Having two things with the same name is not a good idea - but avoiding the use of delimiter in the listing will avoid the problem. Would you like to try with the diff in the linked issue?

**Comment by pvanderlinden** [comment]
Sure, I will try that later today

**Comment by pvanderlinden** [comment]
I did a quick try, but it failed: 
```
~/anaconda3/envs/env/lib/python3.7/site-packages/gcsfs/core.py in rm(self, path, recursive, batchsize)
   1122 
   1123     def rm(self, path, recursive=False, batchsize=20):
-> 1124         paths = self.expand_path(path, recursive=recursive)
   1125         sync(self.loop, self._rm, paths, batchsize=batchsize)
   1126 

~/anaconda3/envs/env/lib/python3.7/site-packages/fsspec/spec.py in expand_path(self, path, recursive, maxdepth)
    722         """Turn one or more globs or directories into a list of all matching files"""
    723         if isinstance(path, str):
--> 724             out = self.expand_path([path], recursive, maxdepth)
    725         else:
    726             out = set()

~/anaconda3/envs/env/lib/python3.7/site-packages/fsspec/spec.py in expand_path(self, path, recursive, maxdepth)
    733                     continue
    734                 elif recursive:
--> 735                     out |= set(self.find(p, withdirs=True))
    736                 # TODO: the following is maybe only necessary if NOT recursive
    737                 out.add(p)

TypeError: find() got an unexpected keyword argument 'withdirs'

```

I don't have any time to check why that happens though.
