### ISSUE TITLE
running into multiple errors with ls and rm under v0.7.0

### ISSUE THREAD

**Issue by nicoa** [dask/gcsfs#282]
**What happened**:
While executing some code I receive a `ERROR:gcsfs.core:_call non-retriable exception: Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.` (while using usual google cloud credentials object and therefore not being anonymous at all).

Trying to debug this I ran into multiple issues. First, I created gcsfs instance without caching (pass cache_timeout=0 to FileSystem Instance while init) and ran into the following:
```python
somewhere/in/some/file.py in some_routine()
--> 150         files =fs.ls(path)

myenv/lib/python3.7/site-packages/gcsfs/core.py in _list_objects(self, path)
    575
    576         try:
--> 577             clisting = self._ls_from_cache(path)
    578             hassubdirs = clisting and any(
    579                 c["name"].rstrip("/") == path and c["type"] == "directory"

myenv/lib/python3.7/site-packages/fsspec/spec.py in _ls_from_cache(self, path)
    319             if len(files) == 0:
    320                 # parent dir was listed but did not contain this file
--> 321                 raise FileNotFoundError(path)
    322             return files
    323         except KeyError:
FileNotFoundError: the_passed_path/with_subfolder
```

After running `fs.invalidate_cache()`, that part of my code started working, while later on `.fs.rm(path, recursive=True)` it ran into `OSError: {"Invalid bucket name: 'gs:'"}` (will provide traceback if necessary).

**What you expected to happen**:
1. No need to invalidate the cache because setting the cache_timeout to zero should lead to not using the cache at all - or are there other methods to avoid this? From what I saw on a first look, the only new stuff is the async execution, not the caching, therefore this is confusing to me where this comes from.
2. `GCSFileSystem.rm` to work and throw away the leading `gs://`.

**Anything else we need to know?**:
occured with new packages, previous: gcsfs 0.6.2, fsspec 0.7.4, now (errors): gcsfs 0.7, fsspec 0.8

**Environment**:

- Dask version: 2.25
- Python version: 3.7
- Operating System: Debian
- Install method: pip

**Comment by martindurant** [comment]
Your issue 2 is fixed in https://github.com/dask/gcsfs/pull/280, which is nearly done.

**Comment by martindurant** [comment]
Pass `use_listings_cache=False` to disable such caching.

**Comment by nicoa** [comment]
nice to hear about the other ticket, thx for referencing!

Regarding point 1: thanks, that worked out! I still run into `Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket`, but this is in an `ls` somewhere deeper in our tooling and I'm not able to reproduce it (seems to be related to asynchronous execution) currently out of this packaged context, therefore would close this ticket and open a new one if I'm able to reproduce it.

Thanks a lot!
