### ISSUE TITLE
gcsfs v0.7.0 overrides python logging in any importing module

### ISSUE THREAD

**Issue by nbren12** [dask/gcsfs#284]
**What happened**:

None of our logging statements are printing to console when we import gcsfs

**What you expected to happen**:

The logging statements should print to console

**Minimal Complete Verifiable Example**:

```python
import gcsfs
import logging
logging.basicConfig(level=logging.INFO)
logging.info("hello")
```

Nothing shows up when I run the above code...

**Anything else we need to know?**:

Here are some suspicious lines of code:
```
$ ag logging                                                                                                                                                                           (base)
auth.py
6:import logging
9:logging.basicConfig()

core.py
21:import logging
39:logger = logging.getLogger(__name__)
40:logging.basicConfig()
136:      containing the JSON returned by logging in with the gcloud CLI tool,

cli/gcsfuse.py
2:import logging
36:    help="Set logging level. '-v' for 'gcsfuse' logging."
37:    "'-v -v' for complete debug logging.",
45:        logging.basicConfig(level=logging.INFO)
46:        logging.getLogger("gcsfs.gcsfuse").setLevel(logging.DEBUG)
48:        logging.basicConfig(level=logging.DEBUG)
52:        logging.basicConfig(level=logging.INFO, format=fmt)
53:        logging.getLogger("gcsfs.gcsfuse").setLevel(logging.DEBUG)
55:        logging.basicConfig(level=logging.DEBUG, format=fmt)
```

**Environment**:

- Dask version: 2.5.2
- Python version: 3.7.3
- Operating System: Mac
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
might be worth reading. Basically, libraries shouldn't mess with config /
handlers.

**Comment by martindurant** [comment]
gcsfs master no longer does this. At https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L40 , we configure a handler for the specific logger, only if an environment variable is set. Otherwise, the logger can be configured by the calling application as required.

**Comment by nbren12** [comment]
Thanks. That sounds good. Is there any chance you could make a patch release with the current master? That would be highly appreciated. 0.7. has several useful fixes and enhancements, but we do need to see our logs.

**Comment by martindurant** [comment]
I anticipate a round of releases mid next week.

**Comment by nbren12** [comment]
Thanks. Feel free to close this issue if you like, since the problem is resolved on master.
