### ISSUE TITLE
call to exists() returns False unless ls() is called first

### ISSUE THREAD

**Issue by jobevers** [dask/gcsfs#286]
**What happened**:

```
>>> fs.exists('[...]/data/2020-08-30/export_log.csv')
DEBUG:gcsfs:GET: b/{}/o/{}, ('[...]', '[...]/data/2020-08-30/export_log.csv'), {}
False
>>> fs.exists('[...]/data/2020-08-30')
True
>>> fs.ls('[...]/data/2020-08-30')
[..., '.../data/2020-08-30/export_log.csv', ...]
>>> fs.exists('[...]/data/2020-08-30')
True
```

**What you expected to happen**:

The first call to exists() should return True

**Environment**:

- gcsfs version: 0.7.1
- Python version: 3.6
- Operating System: ubunt 18.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Does your URL happen to contain the protocol ("gcs://" or "gs://) ? If so, then I think this is fixed in fsspec master.

**Comment by martindurant** [comment]
@jobevers , please check if https://github.com/dask/gcsfs/pull/289 helps

**Comment by martindurant** [comment]
(now in master)
