### ISSUE TITLE
Upload ORC data to GCS 

### ISSUE THREAD

**Issue by MikeChenfu** [dask/gcsfs#291]
Hello, I am using gcsfs to download the orc data to local Server by `cudf` and `dask`. It is good. But I met the problem to upload the results back to GCS. I try something like below code but it failed. I see there are some ways to support `csv` data, but does not work on `orc` data. Appreciate it if anyone has any ideas.
```
import tempfile
tmp = tempfile.mktemp()
df.to_orc(tmp, compression='snappy')
with open(tmp, 'rb') as f:
    fs.upload(path, f, storage_options={"token": "credential"})
    
```

**Comment by martindurant** [comment]
Have you tried
```
fs.upload(path, tmp, storage_options={"token": "credential"})
```
(i.e., don't open the local file yourself) ?

**Comment by martindurant** [comment]
(sorry, edited)

**Comment by MikeChenfu** [comment]
It works! Appreciate it !
