### ISSUE TITLE
Add an environmental for requester_pays

### ISSUE THREAD

**Issue by nbren12** [dask/gcsfs#295]
Because fsspec is so useful, we tend to instantiate many fsspec objects in different parts of our code base (often using the polymorphic `fsspec.filesystem` or `fsspec.get_fs_token_paths` functions. Given this, it is not convenient to add a `requester_pays` option to every single place an fsspec object is instantiated.

Can we make a global configuration option for `requester_pays` available? An environmental variable like `GCSFS_REQUESTER_PAYS=1` would be convenient.

**Comment by martindurant** [comment]
I don't have a strong objection, but it seems to me that there are a whole load of parameters that you might want to treat in a similar way.
In https://github.com/intake/filesystem_spec/issues/339 we muse about setting the default filesystem instance of a protocol and/or setting up a config system which could specify the values of any kwargs that are not explicitly given. Setting that all up would take considerably more effort than having a special case of requester_pays, but would of course be more general.

**Comment by nbren12** [comment]
I agree that a general system would be nice. For convenience, it would be nice to have this be a configuration file or environmental variable rather than a python module which must be installed. In the absence of a general backend configuration system, there already is a precedent for bespoke environmental variables configuring the behavior of the GCS filesystem (e.g. GOOGLE_APPLICATION_CREDENTIALS).

**Comment by martindurant** [comment]
GOOGLE_APPLICATION_CREDENTIALS was inherited from the gcloud suite :) 

Agreed, this should be configuration file(s) and env-var overrides. Dask has such a config system, but we don't want fsspec to depend on other packages if not absolutely essential.

**Comment by nbren12** [comment]
Sure, GOOGLE_APPLICATION_CREDENTIALS comes from the gcloud suite. Nonetheless, I bet many users other than me rely on this variable for authentication with gcsfs, so it has become de-facto public API whether intentionally or not.

Would adding a `GCSFS_REQUESTER_PAYS` variable be okay, or do you want to think more deeply about the config system? We could start with something like this
```
# gcsfs/config.py
import os

requester_pays = os.getenv('GCSFS_REQUESTER_PAYS', '0') == '1'
```
and then add complexity as needed.

**Comment by martindurant** [comment]
I have put some scratch code here: https://github.com/intake/filesystem_spec/pull/453

This allows:
```
$ FSSPEC_GCS_REQUESTER_PAYS=1 python
> import fsspec
> fs = fsspec.filesystem("gcs")
> fs.requester_pays
"1"
> fs = fsspec.filesystem('gcs', requester_pays=False)
> fs.requester_pays
False
```
(note the name of the variable)

This obviously has the problem of having all values be strings, but I can see the path to including structures values in YAML or JSON config files.
