### ISSUE TITLE
Error: Force flush cannot be called more than once

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#30]
My script runs fine remotely - from laptop - but when running on a GCE instance, I get the following error:
```Traceback (most recent call last):
  File "g.py", line 56, in <module>
    recs += 1
  File "xxx/gcsfs/core.py", line 896, in __exit__
    self.close()
  File "xxx/gcsfs/core.py", line 868, in close
    self.flush(force=True)
  File "xxx/gcsfs/core.py", line 754, in flush
    self._initiate_upload()
  File "xxx/gcsfs/core.py", line 798, in _initiate_upload
    self.location = r.headers['Location']
  File "xxx/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Exception ValueError: ValueError('Force flush cannot be called more than once',) in <bound method GCSFile.__del__ of <GCSFile testfile>> ignored
```
Code snippet is:
```
...
            with fs.open(seg_filename, 'wb') as seg_f:
                recs = 0
                while line.startswith(key):
                    seg_f.write(line[line_offset:])
                    line = f.readline()
                    recs += 1
            logger.info('Done writing  {}: {:,} records'.format(seg_filename, recs))
```
Unrelated but I also get a warning `No module named dask.bytes.core`

**Comment by yiga2** [comment]
Turned out to be a permission issue

**Comment by martindurant** [comment]
But still almost a bug: the message shows up when the with-block exits, and the file gets closed, but the file was already closed due to the permissions error.

**Comment by yiga2** [comment]
I spotted the permission issue when changing the block size to less than default (1Mb instead of 5). At that time, GCSFS issued a simple upload – it error’d out but printed partially the html response (403 – Permission Denied). Would be good indeed for either method to get a more explicit message.
