### ISSUE TITLE
does not handle 502 errors (returned by GCS when server is overloaded)

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#31]
I have faced several times the same 502 error when writing in chunks. Errors are sporadic and look like:
```
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 896, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 868, in close
    self.flush(force=True)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 755, in flush
    self._upload_chunk(final=force)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 777, in _upload_chunk
    validate_response(r, self.location)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 111, in validate_response
    raise RuntimeError(m)
RuntimeError: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That's an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That's all we know.</ins>

Exception ValueError: ValueError('Force flush cannot be called more than once',) in <bound method GCSFile.__del__ of <GCSFile tempfile.txt>> ignored
```
Google writes this may happen when system/network is under stress - our script does indeed read and write from `GCS` several GB of files in chunks after on-the-fly transformations.
Look at `Handling Errors` at https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload.
They indicate to implement `exponential-backoff`: https://cloud.google.com/storage/docs/exponential-backoff

Is this something that can be implemented in `GCSFS` i.e. resubmit a chunk when such `5xx` error occurs ?

If not, wrapping the write statement in a try/exception, delete the target file written so far and reprocess is not an option for me. Because the records I write are based off data in a compressed `GCSFS`-file I read. ZipFileExt are not seekable so what is read is gone. I would have to delete the whole batch and restart.

**Comment by martindurant** [comment]
We apparently skip 502 in https://github.com/dask/gcsfs/blob/master/gcsfs/utils.py#L116 - feel free to add. Actually, any >=500 may be reasonable to add here, although I'm not sure what other errors are possible. As the message suggests, though, retrying immediately may not be the right thing to do.

**Comment by martindurant** [comment]
To solve the `ValueError('Force flush cannot be called more than once',)`, could you try moving [this block](https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L825) to the end of that method, after `self._upload_chunk()` ?

**Comment by yiga2** [comment]
Will do.
Retrying is actually per Google the right thing to do:
```
An exponential backoff algorithm retries requests exponentially, increasing the waiting time between retries up to a maximum backoff time. An example is:

1. Make a request to Google Cloud Storage.
2. If the request fails, wait 1 + random_number_milliseconds seconds and retry the request.
3. If the request fails, wait 2 + random_number_milliseconds seconds and retry the request.
4. If the request fails, wait 4 + random_number_milliseconds seconds and retry the request.
```
Unfortunately I am not well versed enough in Python, PR and unit testing to suggest a change - yet !

**Comment by yiga2** [comment]
@martindurant how many lines in the above block did you mean to move: [this one](https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L825:L829) or less ?

**Comment by martindurant** [comment]
https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L825:L826 , just the one block

**Comment by yiga2** [comment]
code move helped get a more explanatory message for other error #33

**Comment by yiga2** [comment]
@martindurant just wondering what's next - will you make the code edit into `core` and add 502 as retriable error code in `utils` (https://cloud.google.com/storage/docs/json_api/v1/status-codes#502_Bad_Gateway) ? 

I made the changes in my own copy but would rather see these in the master.

**Comment by bachsh** [comment]
This issue is marked as closed but the relevant change has been overwritten and now the retriable error codes are `[500, 505]`. Can anyone say why 502 was removed from the list of retriable errors?

**Comment by yiga2** [comment]
@bachsh what makes you say it's removed ? The code is `list(range(500, 505))` so all codes between 500 and 505.
Did you hit a 502 error ? If so, remember it retries only a few times.

**Comment by bachsh** [comment]
whoops, what a n00b :)

yes, we are hitting 502 errors when saving using gcsfs. It makes sense to retry only a few times. Thanks for the answer
