### ISSUE TITLE
Got HttpError, however status code is not printed in log.

### ISSUE THREAD

**Issue by onevirus** [dask/gcsfs#310]
This is error log what I got
```
_call non-retriable exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/gcsfs/core.py", line 507, in _call
    self.validate_response(status, contents, json, path, headers)
  File "/opt/conda/lib/python3.6/site-packages/gcsfs/core.py", line 1230, in validate_response
    raise HttpError({"code": status})
gcsfs.utils.HttpError
```

**What you expected to happen**:
HttpError status code in log.

**Anything else we need to know?**:
I use gcsfs via papermill.
Is there any configuration to print http status code in log ?

**Environment**:

- Dask version: 
- Python version: 3.6
- Operating System: debian
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
The argument to HttpError should also include a "message" to be printed - but the repr of the exception could be changed to include all of the arguments passed to it. Would you like to fix this?
