### ISSUE TITLE
glob() does not error out if bucket cannot be accessed

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#314]
as per the title, in `gcsfs 0.7.1` (and `0.6.2`) if either the file path (e.g. bucket) does not exist or cannot be accessed (permissions), `glob()` does not catch an error and it seems like the function just returns an empty list.

On the other hand, `ls()` does catch the error.

To reproduce:
```
    fs = gcsfs.GCSFileSystem()
    fs.glob("this-bucket-cannot-exist!!!")
    print('No error!')
    fs.ls("this-bucket-cannot-exist!!!")
```
A colleague of mine told me the same happens with `s3fs` so issue may be with `fsspec` lib (0.8.4)

**Comment by martindurant** [comment]
Note that you *do* get not-found or permission-denied if you actually include a glob special character in the path like "notabucket*", "notabucket/*"

**Comment by yiga2** [comment]
You're right. I realize the search pattern is incorrect and using the bucket only does not make sense for globbing.
