### ISSUE TITLE
Harmonize behavior of find command between gcsfs and adlfs

### ISSUE THREAD

**Issue by Darune** [dask/gcsfs#317]
I have the following bucket structure
```
- data/
  - (..lots_of_things)
  - test/
    - test_file.gz
  - test_file.gz
```
what I want it to find any blob with the `data/test` prefix
with gsutils I would do something of the like
`gsutil ls -r data/test*`

Using `#master` version of gcsfs I would do this
```
filesystem.find('data', prefix='test')
```

Now for adlfs i should do the following
```
filesystem.find('data/test')
```
The issue here is that i can't afford to list /data and filter for test on the client side this would take forever and will be rather useless.

It's important to note that for my use case, i would really like to be able to use gcs or abs transparently and thus use the same parameters
however due to this lines in `_do_list_objects`
```
(...)
_path = "" if not _path else _path.rstrip("/") + "/"
prefix = f"{_path}{prefix}" or None
(...)
```

I can not set the path to the path with the prefix since this will add a trailing slash and that's not really what I want.
This is however what I use with adlfs but adlfs doesn't have this `prefix` logic / kwargs.

so I guess the issue here is more a semantic issue, the name of the argument in fsspec is `path` but for storages like this, we use `prefix`.

Would that be ok to not automatically add a trailing slash to the path when no prefix is given ? 
i'm thinking of something like this:

```
query_prefix = "" if not _path else _path
if prefix:
    query_prefix = f"{query_prefix.rstrip('/')}/{prefix.lstrip('/')}"
query_prefix = None if query_prefix == '/' else query_prefix
```

with PathLib this would become

```
query_prefix = "" if not _path else _path
if prefix:
    query_prefix = pathlib.PurePath(f'{query_prefix}/{prefix}')
query_prefix = None if query_prefix == '/' else query_prefix
```

This might however break the usage some have of the find method if they rely on this trailing slash beeing added.

Is this a viable solution for this ?

**Comment by martindurant** [comment]
cc @hayesgb

In general, we have a lot of discussion/problems around accurate representation of paths on object storage within and across the different backends. I am thinking we should convene a group to form standard expectations of the API.

**Comment by Darune** [comment]
I understand that if you mix this with the Local / ftp / github fsspec implementation this might become a real headache. 

The fsspec `find` documentations says:
> List all files below path.
> Like posix `find` command without conditions

This means that `gcsfs`' current implementation is complying to the documentation whereas `adlfs` is not.

Now what I'm trying to do here is more an efficient `glob` for cloud storage instead of a find.
Maybe the introduction of a `prefix_match` / `prefix_find` for specific (Cloud) filesystem is more relevant.

In the meantime, and if i really want to use those two transparently, should I propose a patch to `adlfs` that introduces `prefix` to suit my need ?

**Comment by martindurant** [comment]
> In the meantime, and if i really want to use those two transparently, should I propose a patch to adlfs that introduces prefix to suit my need ?

Maybe give @hayesgb a chance to reply here - otherwise "yes". The same could/should be done for s3fs.

**Comment by hayesgb** [comment]
@martindurant  -- agree that there are significant issues handling path representations across the different backends, and we would benefit from a more comprehensive look at this topic.

@Darune -- Referring specifically to adlfs, I am comfortable with the proposed patch to adlfs.  If you want to submit with a matching test case, that would be great.

**Comment by martindurant** [comment]
Related: https://github.com/intake/filesystem_spec/pull/459

**Comment by Darune** [comment]
closing this since https://github.com/dask/adlfs/issues/152 is solving my issue. Thank to
