### ISSUE TITLE
How to recursive delete objects only

### ISSUE THREAD

**Issue by mikeharbrdata** [dask/gcsfs#333]
I'm experimenting with the "rm" call, and would like to remove all objects within a bucket (recursively). When testing this I observed that the bucket also gets deleted. I'd like to only delete the objects, not the containing bucket, can this be done using the existing call?

**Comment by ajkerrigan** [comment]
Hi @mikeharbrdata - I'm not sure the best way to handle that, but _one_ way would be to use `fs.rm(fs.find('your-bucket'))`. `find` will recursively fetch just the object names under a given path by default, which you can feed into `rm`.

**Comment by martindurant** [comment]
`fs.rm("your-bucket/*", recursive=True)` should work too, but @ajkerrigan 's reply is probably more efficient. 

A *really* cheeky way would be to temporarily remove bucket delete permissions from the user/role.

**Comment by martindurant** [comment]
OK to close?

**Comment by mikeharbrdata** [comment]
Apologies for the delay, we had some use case clarifications on our side so I was able to implement our requirement using the native sdk.

Good to close

**Comment by martindurant** [comment]
OK, don't hesitate to get in touch again
