### ISSUE TITLE
`GCSFileSystem.find` ignores 'withdir' and 'maxdepth' args

### ISSUE THREAD

**Issue by adrianloy** [dask/gcsfs#336]
**What happened**:
I tried to use `GCSFileSystem.find` to list dirs:

```python
import gcsfs
fs = gcsfs.GCSFileSystem(project=gcp_project_name)
bucket_name = "example-bucket"
paths_to_dirs = fs.find(f"gs://{bucket_name}", withdirs=True, maxdepth=2)
```

**What you expected to happen**:

`paths_to_dirs` should contain paths to dirs in the bucket, and should contain at maximum 2 "'/'" in them because of the maxdepth parameter.
However, it only contains paths to files, and the maxdepth parameter seems to be ignored.

Note that glob can not be used anymore to find dirs, so its not straight forward to find a workaround.

**Environment**:

- Gcsfs version: 0.7.1
- Python version: 3.8.5
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I believe https://github.com/dask/s3fs/issues/378 is the same, and a result of the recent efficiency improvement in `find()`. The same resolution, checking specifically for `maxdepth` should work here.

**Comment by adrianloy** [comment]
Thanks for the reply. Looking at the code on master, I think this is already fixed there and only broken in the current release 0.7.1. Will close for now and hope a new release comes soon ;)
