### ISSUE TITLE
get fails with IndexError when using consistency='md5'

### ISSUE THREAD

**Issue by oliverwm1** [dask/gcsfs#338]
**What happened**:
`get` fails when the filesystem is initialized with `consistency='md5'`. If this kwarg was not provided, there was no problem.

**What you expected to happen**:
Object downloads to local filesystem.

**Minimal Complete Verifiable Example**:
Not sure how to reproduce this without this particular GCS object. Can provide more info about the object if that's helpful. The error reliably occurs for certain objects in the bucket, but not for others.

```python
import gcsfs
url = 'gs://*****/2021-01-22-GFS-ICs-2016080100/C384/gfs_data.tile1.nc'
gcsfs.GCSFileSystem(consistency='md5').get(url, 'local.nc')

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-19-0a1b017fa82e> in <module>
      3 url = 'gs://******/2021-01-22-GFS-ICs-2016080100/C384/gfs_data.tile1.nc'
      4 gcsfs.GCSFileSystem().get(url, 'local.nc')
----> 5 gcsfs.GCSFileSystem(consistency='md5').get(url, 'local.nc')

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py in get(self, rpath, lpath, recursive, **kwargs)
    290         lpaths = other_paths(rpaths, lpath)
    291         [os.makedirs(os.path.dirname(lp), exist_ok=True) for lp in lpaths]
--> 292         return sync(self.loop, self._get, rpaths, lpaths)
    293 
    294 

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     69     if error[0]:
     70         typ, exc, tb = error[0]
---> 71         raise exc.with_traceback(tb)
     72     else:
     73         return result[0]

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py in f()
     53             if callback_timeout is not None:
     54                 future = asyncio.wait_for(future, callback_timeout)
---> 55             result[0] = await future
     56         except Exception:
     57             error[0] = sys.exc_info()

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py in _get(self, rpaths, lpaths, **kwargs)
    278             *[
    279                 self._get_file(rpath, lpath, **kwargs)
--> 280                 for lpath, rpath in zip(lpaths, rpaths)
    281             ]
    282         )

~/miniconda3/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py in _get_file(self, rpath, lpath, **kwargs)
   1137                     for bit in r.headers["X-Goog-Hash"].split(",")
   1138                     if bit.split("=")[0] == "md5"
-> 1139                 ][0]
   1140                 assert b64encode(md.digest()).decode().rstrip("=") == dig
   1141 

IndexError: list index out of range
```

**Environment**:

- gcsfs version: v0.7.2
- Python version: 3.7.9
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Looks like the response didn't return any MD5 information. It may be useful to see, via debug, what google did provide in its headers. I'm not sure what the correct behaviour should be if the user wishes to check md5, but it's missing.

**Comment by oliverwm1** [comment]
Okay, running same code as above with environmental variable `GCSFS_DEBUG` set I get:
```
2021-02-05 22:15:40,138 - gcsfs - DEBUG - Connected with method google_default
2021-02-05 22:15:40,139 - gcsfs - DEBUG - GET: b/{}/o/{}, ('vcm-ml-raw-flexible-retention', '2021-01-22-GFS-ICs-2016080100/C384/gfs_data.tile1.nc'), {}
Traceback (most recent call last):
  File "debug_gcsfs.py", line 3, in <module>
    gcsfs.GCSFileSystem(consistency='md5').get(url, 'local.nc')
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py", line 292, in get
    return sync(self.loop, self._get, rpaths, lpaths)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py", line 280, in _get
    for lpath, rpath in zip(lpaths, rpaths)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py", line 1139, in _get_file
    ][0]
IndexError: list index out of range
```
Is there another way to get more debug info?

**Comment by martindurant** [comment]
Yes, please actually run debug (pdb) to find the value of the header that's gailing.

On February 5, 2021 5:28:18 PM EST, Oliver Watt-Meyer <notifications@github.com> wrote:
>Okay, running same code as above with environmental variable
>`GCSFS_DEBUG` set I get:
>```
>2021-02-05 22:15:40,138 - gcsfs - DEBUG - Connected with method
>google_default
>2021-02-05 22:15:40,139 - gcsfs - DEBUG - GET: b/{}/o/{},
>('vcm-ml-raw-flexible-retention',
>'2021-01-22-GFS-ICs-2016080100/C384/gfs_data.tile1.nc'), {}
>Traceback (most recent call last):
>  File "debug_gcsfs.py", line 3, in <module>
>    gcsfs.GCSFileSystem(consistency='md5').get(url, 'local.nc')
>File
>"/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py",
>line 292, in get
>    return sync(self.loop, self._get, rpaths, lpaths)
>File
>"/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py",
>line 71, in sync
>    raise exc.with_traceback(tb)
>File
>"/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py",
>line 55, in f
>    result[0] = await future
>File
>"/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py",
>line 280, in _get
>    for lpath, rpath in zip(lpaths, rpaths)
>File
>"/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py",
>line 1139, in _get_file
>    ][0]
>IndexError: list index out of range
>```
>Is there another way to get more debug info?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/gcsfs/issues/338#issuecomment-774322289

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oliverwm1** [comment]
Okay the full header is below. The `'X-Goog-Hash'` item is `'crc32c=01crjw=='`.
```
-> bit.split("=")[1]
(Pdb) p r.headers
<CIMultiDictProxy('X-GUploader-UploadID': 'ABg5-Uxz0U4O_telU2cqyIJKcwdWsr-94Z0eY8pgBICnW-siKL-x7vGAGbb5N5NMv-MD56bhVjbz746XfZywV3NUCpU', 'Etag': 'CK2SwIvTr+4CEAE=', 'X-Goog-Hash': 'crc32c=01crjw==', 'Content-Type': 'application/x-netcdf', 'Content-Language': 'en', 'X-Goog-Generation': '1611322235029805', 'X-Goog-Metageneration': '1', 'X-Goog-Storage-Class': 'STANDARD', 'Pragma': 'no-cache', 'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Content-Disposition': 'attachment', 'Date': 'Sun, 07 Feb 2021 17:26:30 GMT', 'Vary': 'Origin', 'Vary': 'X-Origin', 'Content-Length': '341330692', 'Server': 'UploadServer')>
```

**Comment by martindurant** [comment]
Right, so google is supposed to provide MH5, but for some reason only sent CRC. I suppose raising an error is the right thing to do - but with a better message. I wonder if we can track down why MD5 is missing in the response.

**Comment by oliverwm1** [comment]
It's possible the file was uploaded with a parallel composite upload (I'll confirm and get back on this) in which case we'd expect it to be missing: https://cloud.google.com/storage/docs/xml-api/reference-headers#xgooghash

I can make a PR to provide a better message.

**Comment by martindurant** [comment]
Thank you, it is appreciated.
