### ISSUE TITLE
Check crc32c checksums

### ISSUE THREAD

**Issue by nbren12** [dask/gcsfs#342]
GCSFS will sometimes fail to download data when `consistency="md5"` (see https://github.com/VulcanClimateModeling/fv3config/issues/124).

According to google cloud storage's [docs](https://cloud.google.com/storage/docs/composite-objects#metadata) not all GCS objects have md5 metadata. They recommend using "crc32c" instead since apparently all objects have it.  

After toying around with the python library `crcmod`, this is how one computes the "crc32c" of a bunch of bytes:
```
In [41]: crc32c = crcmod.Crc(0x11EDC6F41, initCrc=0, xorOut=0xFFFFFFFF)

In [42]: crc32c.update(data)

In [43]: crc32c.hexdigest()
Out[43]: '4C349160'
```
I got the random looking hexadecimal numbers from wikipedia. I verified that this checksum works using the google-cloud-storage library. The usage looks pretty similar to "md5". I'm happy to contribute a PR adding a `consistency="crc32c"` option if ya'll are open to it.

**Comment by martindurant** [comment]
Yes please!
