### ISSUE TITLE
get fails when filesystem initialized with consistency='crc32c'

### ISSUE THREAD

**Issue by oliverwm1** [dask/gcsfs#347]
**What happened**:

`NotImplementedError` raised when calling `get` with a filesystem initialized with consistency='crc32c'

**What you expected to happen**:

File would get copied.

**Minimal Complete Verifiable Example**:

```python
>>> gcsfs.GCSFileSystem(consistency='crc32c').get('gs://bucket/object', 'local_file')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/fsspec/asyn.py", line 294, in get
    return sync(self.loop, self._get, rpaths, lpaths)
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/fsspec/asyn.py", line 279, in _get
    return await asyncio.gather(
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/gcsfs/core.py", line 1227, in _get_file
    checker.validate_http_response(r)
  File "/home/OliWM/miniconda3/envs/test-gcsfs/lib/python3.9/site-packages/gcsfs/checkers.py", line 95, in validate_http_response
    raise NotImplementedError()
NotImplementedError
```

**Anything else we need to know?**:

Although `crc32c` consistency checking not implemented for all methods, I thought it would work for `get`.

**Environment**:

- gcsfs version: v0.7.2
- crcmod version: v1.7

@nbren12

**Comment by nbren12** [comment]
To debug this it would be nice to reenable the get/put tests on master. These are currently skipped in CI:

```
 gcsfs/tests/test_core.py::test_get_put[None] SKIPPED (async fail)        [ 40%]
gcsfs/tests/test_core.py::test_get_put[size] SKIPPED (async fail)        [ 41%]
gcsfs/tests/test_core.py::test_get_put[md5] SKIPPED (async fail)         [ 42%]
gcsfs/tests/test_core.py::test_get_put[crc32c] SKIPPED (async fail)      [ 43%]
gcsfs/tests/test_core.py::test_get_put_recursive[] SKIPPED (async fail)  [ 44%]
gcsfs/tests/test_core.py::test_get_put_recursive[gs://] SKIPPED (asy...) [ 45%]
gcsfs/tests/test_core.py::test_get_put_recursive[gcs://] SKIPPED (as...) [ 46%]
gcsfs/tests/test_core.py::test_get_put_file_in_dir[] SKIPPED (async ...) [ 47%]
gcsfs/tests/test_core.py::test_get_put_file_in_dir[gs://] SKIPPED (a...) [ 48%]
gcsfs/tests/test_core.py::test_get_put_file_in_dir[gcs://] SKIPPED (...) [ 50%]
```

**Comment by martindurant** [comment]
> Although crc32c consistency checking not implemented for all methods, I thought it would work for get.

I believe you might just need to instal `crcmod`, which was not obvious.

Does anyone know if the builtin `zlib.crc32` can do this? We need crc32c, specifically. Then there would be no dependency. 

> it would be nice to reenable the get/put tests on master

That was not supposed to happen... Seems like a few issues have accumulated here, this repo could use a little tlc.

**Comment by oliverwm1** [comment]
> I believe you might just need to instal crcmod, which was not obvious.

`crcmod` was installed (error would get raised at different line if the import failed).

**Comment by martindurant** [comment]
OK, thanks. I may get to this soon, but it should be an easy fix, I think, if you would like to have a go.

**Comment by nbren12** [comment]
Thanks @martindurant. Let me know if I can help. I think we need to implement `validate_http_response` for the crc32c checker.

**Comment by nbren12** [comment]
Thanks!
