### ISSUE TITLE
isdir()/info() doesn't work properly for

### ISSUE THREAD

**Issue by isidentical** [dask/gcsfs#349]
When an empty directory created (with a trailing slash), the initial `info()` call returns the object itself and also caches but the call after that returns it in the form of a directory instead of the just what it got from API call. Here is a simple reproducer (first isdir() returns False, second one returns True);
 
```py
import secrets
from gcsfs import GCSFileSystem
from pprint import pprint

BUCKET = <FILL HERE>
BASE_PATH = BUCKET + "/" + secrets.token_hex(12)
EMPTY_DIR = BASE_PATH + "/empty_dir/"

fs = GCSFileSystem()
fs.makedirs(BASE_PATH)
fs.touch(EMPTY_DIR)

print("isdir()?", fs.isdir(EMPTY_DIR))
print("isdir() (cached)?", fs.isdir(EMPTY_DIR))

fs.invalidate_cache()
print("\nInitial call: ")
pprint(fs.info(EMPTY_DIR))
print("\nSecondary call (from cache): ")
pprint(fs.info(EMPTY_DIR))
```

```
isdir()?  False
isdir() (cached)? True

Initial call: 
{'bucket': 'batuhan-test',
 'contentType': 'application/octet-stream',
 'crc32c': 'AAAAAA==',
 'etag': 'COeb0Jbagu8CEAE=',
 'generation': '1614175995694567',
 'id': 'batuhan-test/39bd4b9d6b4a71c8fd857e5d/empty_dir//1614175995694567',
 'kind': 'storage#object',
 'md5Hash': '1B2M2Y8AsgTpgAmY7PhCfg==',
 'mediaLink': 'https://www.googleapis.com/download/storage/v1/b/batuhan-test/o/39bd4b9d6b4a71c8fd857e5d%2Fempty_dir%2F?generation=1614175995694567&alt=media',
 'metageneration': '1',
 'name': 'batuhan-test/39bd4b9d6b4a71c8fd857e5d/empty_dir/',
 'selfLink': 'https://www.googleapis.com/storage/v1/b/batuhan-test/o/39bd4b9d6b4a71c8fd857e5d%2Fempty_dir%2F',
 'size': 0,
 'storageClass': 'STANDARD',
 'timeCreated': '2021-02-24T14:13:15.696Z',
 'timeStorageClassUpdated': '2021-02-24T14:13:15.696Z',
 'type': 'file',
 'updated': '2021-02-24T14:13:15.696Z'}

Secondary call (from cache): 
{'bucket': 'batuhan-test',
 'name': 'batuhan-test/39bd4b9d6b4a71c8fd857e5d/empty_dir',
 'size': 0,
 'storageClass': 'DIRECTORY',
 'type': 'directory'}
```

**Comment by isidentical** [comment]
The initial, uncached call goes through here and returns the result in the raw format;
https://github.com/dask/gcsfs/blob/30f9a875c4ea4588339388c17203ac0474b8e840/gcsfs/core.py#L825-L826

but the second one (since it is cached) gets returned here and result in the proper format;
https://github.com/dask/gcsfs/blob/30f9a875c4ea4588339388c17203ac0474b8e840/gcsfs/core.py#L815-L823

**Comment by martindurant** [comment]
> When an empty directory created (with a trailing slash)

I'll look into this, but I must note that GCS does *not* have directories, whether or not there is a trailing "/". I would recommend against trying to directly create directories.

What difference am I supposed to see between the first and second calls? `isdir()` returns `False` both times, and the info details look the same.

**Comment by isidentical** [comment]
> What difference am I supposed to see between the first and second calls? isdir() returns False both times, and the info details look the same.

I apparently shared the output for the wrong script, can you check it again (updated the original post).

**Comment by isidentical** [comment]
> I'll look into this, but I must note that GCS does not have directories, whether or not there is a trailing "/". I would recommend against trying to directly create directories.

Yes, though empty-objects with trailing slash considered sort of directories (at least that is what the current code does, under the cache), https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork.

**Comment by martindurant** [comment]
OK: the code in `_info` is wrong, this is not a directory. Previously we only cached the info block from directories and not files, and this block apparently was not updated. It would be informative to figure out where the cache is being populated, it's not immediately obvious to me (I would info/isdir to return from `return await self._get_object(path)` without saving the entry).

**Comment by isidentical** [comment]
Checked with s3fs/adlfs, they also claim these are files instead of directories. By the way, FWIW these file/directories can be created using `create folder` button on the aws/google cloud UI, so it is kind of controversial to assume these are files but they are not exactly directories either. Maybe it should be explicitly documented, or just a flag in the Spec that denotes this file system doesn't have the concept of directories.

**Comment by martindurant** [comment]
You will find similar discussions in other issues on this repo and elsewhere - and it does confuse people. I don't know what or where we can write to clarify this. I mention this briefly in [my webinar](https://know.anaconda.com/CommonPitfalls-LP.html?utm_medium=resources&utm_source=anaconda&utm_campaign=events).

To be sure, the CLI only emulates directories in certain cases (thanks for the link) and the REST API and SKD clients do not so this at all. I would say that the console, with its "create folder" button is definitely the odd one out.

**Comment by isidentical** [comment]
Looks like this is a duplicate of #312
