### ISSUE TITLE
Docs typo?

### ISSUE THREAD

**Issue by max-sixty** [dask/gcsfs#352]
**What happened**:

Should this be `True`, (and `loop=loop`)?

> If you wish to call gcsfs from async code, then you should pass asynchronous=False, loop= to the constructor (the latter is optional, if you wish to use both async and sync methods). You must also explicitly await the client creation before making any GCS call.

https://gcsfs.readthedocs.io/en/latest/#async

**Comment by martindurant** [comment]
Erm, oops? Please feel free to correct in a PR.

**Comment by martindurant** [comment]
Would you like to fix this @max-sixty ?

**Comment by max-sixty** [comment]
@martindurant I missed this! 

I need to run through a small-but-not-instant process to contribute to a new library. I will do that and make the change in the coming weeks.
