### ISSUE TITLE
Verify that Read the Docs is building after master -> main

### ISSUE THREAD

**Issue by jsignell** [dask/gcsfs#359]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by jrbourbeau** [comment]
Just checking in here, @martindurant is RTD pointing to `main`? Looking at the [RTD builds](https://readthedocs.org/projects/gcsfs/builds/) there have been some recent builds, but I wanted to double check

**Comment by martindurant** [comment]
Yes, it points to main. THyew!
