### ISSUE TITLE
Always tries to validate headers with md5

### ISSUE THREAD

**Issue by isidentical** [dask/gcsfs#360]
Even though the consistency checker is set to None, the gcsfs always tries to validate the contents of a response when x-goog-hash is present with md5. 
https://github.com/dask/gcsfs/blob/85eb01886c9303af4dde20500a0b81d0055b41e1/gcsfs/core.py#L1348-L1351

The problem with that is `x-goog-hash` is not only specific to md5, the hash might be a crc32 when the object is composite. So the operation throws a `NotImplementedError` and fails abruptly. 

For the check above, either it should check if the consistency setting is `md5` (`self.consistency == 'md5'`), or handle it with try/except in case it fails (`try: checker.check() except NotImplementedError: pass`), or should be completely gone (since it kinda seems like over doing). I could have submitted a patch though there are 3 different actions that might be taken so I'm just posting the issue now

**Comment by isidentical** [comment]
CC: @martindurant

**Comment by martindurant** [comment]
Yes, I agree with your line of reasoning here, the checker should match the parent file system's, or should be settable by the user in `open`.
