### ISSUE TITLE
metadata and content-type properties incorrect on GCSFile reading

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#366]
Tested on 0.7.2, when opening a file for reading, the `metadata` and `content-type` properties - possibly more - in GCSFile() are not copied from the `details` dict e.g. `size` is.

![image](https://user-images.githubusercontent.com/25224265/113186454-b0a54b00-9225-11eb-801e-200f8c6cb7ad.png)

**Comment by martindurant** [comment]
Should be easy to fix, right?

**Comment by yiga2** [comment]
Think so - workaround is obvious, query `details` instead, but not sure if the fix is in `gcsfs or `fsspec`.

**Comment by martindurant** [comment]
Like this?
```diff
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -1400,10 +1400,10 @@ class GCSFile(fsspec.spec.AbstractBufferedFile):
         self.gcsfs = gcsfs
         self.bucket = bucket
         self.key = key
-        self.metadata = metadata
+        self.metadata = metadata or self.details.get("metadata", {})
         self.acl = acl
         self.checker = get_consistency_checker(consistency)
-        self.content_type = content_type or "application/octet-stream"
+        self.content_type = content_type or self.details.get("contentType", "application/octet-stream")
```

**Comment by martindurant** [comment]
(to be checked in write mode too, when I'm not immediately certain what `details` should contain)

**Comment by yiga2** [comment]
Is it `fsspec.spec.AbstractBufferedFile` setting `metadata` and `content_type` to start with ? If so, I would look how/why it didn't copy over as `size` property for instance is copied correctly.
But otherwise, you are spot on.
