### ISSUE TITLE
Get unexpected keyword argument 'callback_timeout' when creating GCSFileSystem object on Windows

### ISSUE THREAD

**Issue by pcotteadvestis** [dask/gcsfs#372]
Hello everyone,

**What happened**:
I am working on a Windows Server machine on Google Cloud Plateform, with Python 3.8. I am trying to create a GCSFileSystem object with asynchronous=False. No multiprocessing, no dask, just good old serial Python. I get the following exception :

```
>>> gcsfs.GCSFileSystem(asynchronous=False)
Exception ignored in: <function ClientSession.__del__ at 0x0000005A7B51FA60>
Traceback (most recent call last):
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\aiohttp\client.py", line 326, in __del__
    if not self.closed:
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\aiohttp\client.py", line 963, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\fsspec\spec.py", line 69, in __call__
    obj = super().__call__(*args, **kwargs)
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\gcsfs\core.py", line 269, in __init__
    self._session = sync(
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\fsspec\asyn.py", line 53, in sync
    raise result[0]
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\fsspec\asyn.py", line 20, in _runner
    result[0] = await coro
  File "C:\Users\advestis\PycharmProjects\venvs\transparentpath\lib\site-packages\fsspec\implementations\http.py", line 25, in get_client
    return aiohttp.ClientSession(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'callback_timeout'
>>>
```

**Minimal Complete Verifiable Example**:

```python
import gcsfs
gcsfs.GCSFileSystem(asynchronous=True)  # works fine
gcsfs.GCSFileSystem(asynchronous=False)  # TypeError: __init__() got an unexpected keyword argument 'callback_timeout'
gcsfs.GCSFileSystem()  # TypeError: __init__() got an unexpected keyword argument 'callback_timeout'
```

**Anything else we need to know?**:

It *might* have something to do with the following PR :  #326 
I can't be sure since I did not try with an earlier version.

I do not specify any credentials. 

**Environment**:

- Python version: 3.8
- gcsfs version: 0.7.2
- Operating System: Microsoft, Windows Server, 2012 R2 Datacenter, Server with Desktop Experience, x64 built on 20201208, supports Shielded VM features
- Install method (conda, pip, source): `pip install gcsfs` in a virtualenv

Thanks in advance for any advice, or better for a bug fix ;)

**Comment by martindurant** [comment]
What versions of fsspec and gcsfs do you have?

**Comment by sroj** [comment]
We were having the same issue a few hours ago, with `gcsfs==0.7.2` and `fsspec==0.8.7`.
Updating to `gcsfs==0.8.0` and pinning fsspec to `fsspec==0.9.0` fixed it for us (which is pretty much what this relevant, but not yet released [PR](https://github.com/dask/gcsfs/pull/371) is doing).

**Comment by pcotteadvestis** [comment]
> What versions of fsspec and gcsfs do you have?

Sorry I forgot to mention it in the original post (now editted) : the version is 0.7.2

Also, please note that there is no problem at all on Ubuntu 18.

**Comment by martindurant** [comment]
What versions of fsspec and gcsfs do you have?

Please install fsspec 0.9.0 with gcsfs 0.8.0 OR fsspec 0.8.x with gcsfs 0.7.x.

**Comment by pcotteadvestis** [comment]
> What versions of fsspec and gcsfs do you have?
> 
> Please install fsspec 0.9.0 with gcsfs 0.8.0 OR fsspec 0.8.x with gcsfs 0.7.x.

Hi, I have gcsfs 0.7.2. I tried with gcsfs 0.8.0 and fsspec 0.9.0, it seems to be working. Thank you !
