### ISSUE TITLE
Recursively deleting all objects in bucket fails on gcsfs 0.7.2 with "list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by james-tisato-kortical** [dask/gcsfs#374]
**What happened**:
After upgrading from gcsfs 0.7.1 to 0.7.2, previously-working code that recursively deletes all objects in a bucket now fails:
```
File "test.py", line 15, in <module>
    fs.rm(f'{bucket_name}/**', recursive=True)
  File "/home/james/dev/venvs/test/lib/python3.8/site-packages/gcsfs/core.py", line 1230, in rm
    paths = self.expand_path(path, recursive=recursive)
  File "/home/james/dev/venvs/test/lib/python3.8/site-packages/fsspec/spec.py", line 806, in expand_path
    out = self.expand_path([path], recursive, maxdepth)
  File "/home/james/dev/venvs/test/lib/python3.8/site-packages/fsspec/spec.py", line 818, in expand_path
    self.expand_path(
  File "/home/james/dev/venvs/test/lib/python3.8/site-packages/fsspec/spec.py", line 824, in expand_path
    rec = set(self.find(p, maxdepth=maxdepth, withdirs=True))
  File "/home/james/dev/venvs/test/lib/python3.8/site-packages/gcsfs/core.py", line 1164, in find
    par = self._parent(o["name"])
TypeError: list indices must be integers or slices, not str
```

**What you expected to happen**:
All objects in the bucket would be deleted but the bucket itself would remain.

**Minimal Complete Verifiable Example**:

```python
from gcsfs import GCSFileSystem
from uuid import uuid4

bucket_name = str(uuid4())
print(f'Bucket name: {bucket_name}')

# Create bucket and add some objects
fs = GCSFileSystem()
fs.mkdir(bucket_name)
fs.touch(f'{bucket_name}/root.txt')
fs.touch(f'{bucket_name}/subdir/1.txt')

# Delete all objects recursively
fs.rm(f'{bucket_name}/**', recursive=True)
```

**Anything else we need to know?**:
This started happening after I tried updating from `gcsfs` 0.7.1 to 0.7.2. I also tried updating to later versions of `gcsfs` and `fsspec` (up to 0.8.0 and 0.9.0 respectively) but the error remains.

**Environment**:

- gcsfs version: 0.7.2
- fsspec version: 0.8.5
- Python version: 3.8.8
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
While agree that this should work, I would point out that "**" in the path already implies recursive. The following both work to delete all files within the bucket (but not the bucket itself)
```
fs.rm(bucket_name + "/*", recursive=True)
fs.rm(bucket_name + "/**")
```
I think you are effectively listing all files and then calling find of each of them, including ones that are not directories.

**Comment by james-tisato-kortical** [comment]
Thanks for the quick reply. 

We have been using `fs.rm(f'{bucket_name}/**', recursive=True)` because on previous gcsfs versions `fs.rm(f'{bucket_name}/*', recursive=True)` doesn't actually delete recursively - if I make this change to the example code, the root.txt object is removed but the subdirectory and its content remain.

I see now that `fs.rm(bucket_name + "/**")` does work, so thank you for that. However, `fs.rm(bucket_name + "/*", recursive=True)` on gcsfs 0.7.2 produces the same error as I described in the original bug report.

**Comment by martindurant** [comment]
I am testing on 0.8.0 and it seems to be OK - is that fine with you?

**Comment by james-tisato-kortical** [comment]
Ah, I hadn't tried that. I just gave it a go and I can see it works fine. Thanks for clarifying!
