### ISSUE TITLE
Ability to pass parameters to ` aiohttp.ClientSession()` (e.g. for proxy settings)

### ISSUE THREAD

**Issue by jim-pansn** [dask/gcsfs#392]
I was not able to find a way to apply proxy settings when using gcsfs to load files. 

As far as my understanding goes the follwing is the problem:
- the underlying requests are sent via `aiohttp` 
- aiohttp does not care about the environemt variables HTTP_PROXY or HTTPS_PROXY by default (see https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=proxy#proxy-support)
- to change this behaviour you need to pass arguments to the aiohttp.Session constructor which is called in https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/http.py#L25
-  but unfortunately the get_client() function is called without any parametes in https://github.com/dask/gcsfs/blob/main/gcsfs/core.py#L251

It might be that I'm missing something here. If so, please enlighten me ;-)

If I'm right, then I think it would be very useful to be able to sent parameters to the aiohttp.ClientSession.
Maybe in a similar manner like the pass through of the `storage_options` parameter.

Any help on this issue is highly apreciated. 
Thank you very much and have a nice day,

Janos

**Comment by martindurant** [comment]
That sounds about right.
The problem you will face in implementing this is, is that we won't be able to run tests in CI.

**Comment by jim-pansn** [comment]
I see your point. You could test that the parameter will be passed successfully to the ClientSession and then it is their responsibility to make sure it actualy has an effect. 
It would be very sad if it is not possible to use gcsfs if you need to go through a proxy. 
Do you see any other possiblity to support proxys?

**Comment by martindurant** [comment]
You are right, that would be a reasonable minimal test: to introspect the created aiohttp session referenced by the GCSFileSystem and see that it has the proxy set. You'd have to figure out how to do that! On the other hand, I may accept passing other such parameters through so long as nothing breaks when you pass none. I agree that this is a very useful thing to allow.

**Comment by mlisovyi** [comment]
This feature would be extremely helpful in our environment (where we actively use company proxies)

**Comment by martindurant** [comment]
ping - would anyone on this thread be interested in implementing this? It ought not to bee too hard.

**Comment by jim-pansn** [comment]
I could give it a try but I can't mak any promises on the timeline at the moment...

**Comment by martindurant** [comment]
Does the following do what you want?
```diff
diff --git a/gcsfs/core.py b/gcsfs/core.py
index 49a4262..252ddf0 100644
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -204,6 +204,7 @@ class GCSFileSystem(AsyncFileSystem):
         requests_timeout=None,
         requester_pays=False,
         asynchronous=False,
+        session_kwargs=None,
         loop=None,
         timeout=None,
         **kwargs,
@@ -227,6 +228,7 @@ class GCSFileSystem(AsyncFileSystem):
         self.requests_timeout = requests_timeout
         self.timeout = timeout
         self._session = None
+        self.session_kwargs = session_kwargs

         self.credentials = GoogleCredentials(project, access, token, check_connection)

@@ -251,7 +253,7 @@ class GCSFileSystem(AsyncFileSystem):

     async def _set_session(self):
         if self._session is None:
-            self._session = await get_client()
+            self._session = await get_client(**self.session_kwargs)
         return self._session
```

**Comment by jim-pansn** [comment]
Hi, thanks a lot. This looks like exactly what I thought of. 
What about the `if not self.asynchronous:` case? I think we need to pass the `session_kwargs` there as well. 

`if not self.asynchronous:
            self._session = sync(
                self.loop, get_client, timeout=self.timeout, **session_kwargs
            )
            weakref.finalize(self, self.close_session, self.loop, self._session)`

**Comment by jim-pansn** [comment]
Awesome, thank you a lot!!
