### ISSUE TITLE
Error during glob: TypeError: list indices must be integers or slices, not str"   

### ISSUE THREAD

**Issue by amatsukawa** [dask/gcsfs#393]
**What happened**:

I am getting this error on a call to `.glob` after upgrading gcsfs and fsspec both to `2021.05.0`. 
The exact same code works with `gcsfs=0.6.1` and `fsspec=0.6.2`. The only difference between the two envs that work and don't is the versions of these two libraries (and whatever version changes that may have induced indirectly in the respective envs to other packages).
```
  File "/deps/envs/deps/lib/python3.7/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/deps/envs/deps/lib/python3.7/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/deps/envs/deps/lib/python3.7/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/deps/envs/deps/lib/python3.7/site-packages/gcsfs/core.py", line 637, in _glob
    return await super()._glob(path, prefix=prefix, **kwargs)
  File "/deps/envs/deps/lib/python3.7/site-packages/fsspec/asyn.py", line 435, in _glob
    root, maxdepth=depth, withdirs=True, detail=True, **kwargs
  File "/deps/envs/deps/lib/python3.7/site-packages/gcsfs/core.py", line 943, in _find
    par = o["name"]
TypeError: list indices must be integers or slices, not str"   
```

**What you expected to happen**:
For the glob to continue to work. The glob format I am using has is a wildcard like `gs://bucket/some/path/prefix_*.txt`.

**Minimal Complete Verifiable Example**:
Here is where things get strange. When I fire up the interpreter in the same conda environment that is producing this error, and try the same glob pattern, everything works fine. Unfortunately executing this code path in the exact way this error is produced is very hard to intercept (remote cluster, inside of a container, etc etc). 

**Anything else we need to know?**:
I realize below is a somewhat vague bug report. I hope to get some suggestions as to where to look, so I can produce more useful information.

**Environment**:

- Dask version: 2.18.1
- Python version: 3.7
- Operating System: centos
- Install method (conda, pip, source): conda. also tried pip via conda's env.yml under the `-pip` section, same result.

**Comment by martindurant** [comment]
I cannot reproduce your error, so anything you can do to find out the specific situation under which is happens would be appreciated.

**Comment by amatsukawa** [comment]
Thanks, I will try to recreate the env exactly and report back. I was hoping you'd maybe have some guess like "library X used to return lists but now returns dicts so that's the thing that is out of date" or something along those lines :)

**Comment by martindurant** [comment]
I imagine, it's the `detail=` parameter getting lost somewhere (list of names versus list of dicts)

**Comment by martindurant** [comment]
Also, it might depend on whether the directory has already been listed.

**Comment by amatsukawa** [comment]
Ok, I tried to get the sequence of commands that are run to see if it could lead to a reproducer, it did not. Basically a few `.exists` and then the `.glob` that fails, but trying that sequence locally is fine. I cannot actually intervene (eg. with a pdb) in actual process that produces this error, so I'm at a little bit of a loss on how to further provide useful info.

However, your hunch appears to be correct that it's cache related. If I pass `cache_timoue=-1` when I construct the filesystem, then I don't get the error.

**Comment by isidentical** [comment]
I also have no reproducer (still trying to find one, but quite hard), but we also hit the same issue with `.find() w/prefix`. https://github.com/iterative/dvc/issues/6244

**Comment by isidentical** [comment]
Even though I still have no reproducers, I started to notice that this codepath might be wrong when `prefix` is given. https://github.com/dask/gcsfs/blob/17e7a093613f3ff13544a1503aa79dbfc39eef14/gcsfs/core.py#L940-L948

**Comment by isidentical** [comment]
Reproducer;
```py
import secrets
from gcsfs import GCSFileSystem

bucket = "<bucket>"
random_dir = bucket + "/" + secrets.token_hex(16)

fs = GCSFileSystem(token="<token.json>")

# create a bunch of files
fs.touch(random_dir + "/test_1")
fs.touch(random_dir + "/test_2")
fs.invalidate_cache()

# populate cache
fs.ls(random_dir)

# run the find()
fs.find(random_dir, prefix="non_existing_prefix_")
```

**Comment by martindurant** [comment]
OK, thanks for working up a test, we can proceed with that. I'll get back to you when I have a little time (unless you give it a go first).

**Comment by isidentical** [comment]
I am not really familiar with gcsfs's internals, though from what I understand `_get_object()` shouldn't return directories, so a possible fix that I can think of is this;
```diff
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -380,11 +380,11 @@ class GCSFileSystem(AsyncFileSystem):
         # Check if parent dir is in listing cache
         listing = self._ls_from_cache(path)
         if listing:
-            f = [f for f in listing if f["type"] == "file"]
-            if f:
-                return f
-            # parent is listed, doesn't contain the path
-            raise FileNotFoundError(path)
+            for file_details in listing:
+                if file_details["type"] == "file" and file_details["name"] == path:
+                    return file_details
+            else:
+                raise FileNotFoundError(path)
  
         if not key:
             # Attempt to "get" the bucket root, return error instead of
```
and also this, since even though the previous reproducer probably not fail after this, it is still wrong to try to get path if there is a prefix
```diff
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -937,7 +937,7 @@ class GCSFileSystem(AsyncFileSystem):
             delimiter=None,
             prefix=prefix,
         )
-        if not out and key:
+        if not prefix and not out and key:
             try:
                 out = [
                     await self._get_object(
```

I don't think that I can also generate the VCRs, so if you think that these changes are correct feel free to convert them to a PR. (I can verify that these changes fix both the script above and also the test I added for DVC to check for this case).

**Comment by martindurant** [comment]
You should be able to record VCR so long as you have a GCP account, but I can have a look soon.
