### ISSUE TITLE
gcsfs==2021.06 breaks customized retriable errors 

### ISSUE THREAD

**Issue by TiansuYu** [dask/gcsfs#402]
Related to [Issue 290 ](https://github.com/dask/gcsfs/issues/290). 

We are heavy users of google buckets. And the notorious google 400 issue have caused us a lot of problems in the past. The symptoms is very simple, once you have a google 400 issue, your entire pipeline comes into a halt, and everything is dead-hanging without any warning, until the timeout is reached. The frequency is quite low for this problem. But for a project with hundreds of tests relying on gcsfs and the tests running multiple times per day, you will meet 400 almost every 2 days. 

Our solution relies on the previous solution mentioned in issue 290 before, but until recently, this function has been moved into a private module gcsfs.retry and cannot be accessed any more using the same method. 

So here I want to ask if you could list it into `__init__` so individuals can still handle retry through modifying gcsfs without having to resort to extra tools like dask or prefect for retry handling. (Currently, if i call `gcsfs.retry.is_retriable`, the module will not be found.) 

Ideally, we would like to use latest fsspec, gcsfs and the whole franchise as much as possible. But this problem pinned us to an older version before June for the whole fsspec famility libs, which is not great, especially for integrating with adlfs. 

If an update from your side is not possible, also would love to hear your opinion on any potential workarounds.

**Comment by martindurant** [comment]
> Our solution relies on the previous solution mentioned in issue 290 before, but until recently, this function has been moved into a private module gcsfs.retry and cannot be accessed any more using the same method.

I'm sorry, I don't follow you. `gcsfs.retry` is totally accessible. Would you mind sharing your code that isn't working and showing the error/traceback you get? 

Yes, I would be completely happy to import names from `gcsfs.retry` into `gcsfs` - which do you need? Indeed, it may be simpler for you to put the required imports into a PR.

**Comment by TiansuYu** [comment]
Thx, I will write a PR for it.

**Comment by TiansuYu** [comment]
Thx, you have just reminded me a mistake I have done during the upgrade. Thx a lot. Now the problem is solved.
