### ISSUE TITLE
`is_retriable` is catching 404 responses

### ISSUE THREAD

**Issue by mouradmourafiq** [dask/gcsfs#405]
**What happened**:

[is_retriable](https://github.com/dask/gcsfs/blob/main/gcsfs/retry.py#L54) is catching 404 responses and retrying several times:

```
_get_file_request out of retries on exception: 404, message='Not Found', ...
```

This behavior happens because `ClientResponseError` is not an `HttpError` subclass, so the status code is not even checked:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gcsfs/retry.py", line 110, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gcsfs/core.py", line 993, in _get_file_request
    r.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
```

**What you expected to happen**:

I expect that the status code to be respected here:

```python
errs = list(range(500, 505)) + [
        # Request Timeout
        408,
        # Too Many Requests
        429,
    ]
```

I also think that any `ClientResponseError`will be retried because it's a child of `ClientError`:

```python
    return isinstance(exception, RETRIABLE_EXCEPTIONS)
```

```python
RETRIABLE_EXCEPTIONS = (
    requests.exceptions.ChunkedEncodingError,
    requests.exceptions.ConnectionError,
    requests.exceptions.ReadTimeout,
    requests.exceptions.Timeout,
    requests.exceptions.ProxyError,
    requests.exceptions.SSLError,
    requests.exceptions.ContentDecodingError,
    google.auth.exceptions.RefreshError,
    aiohttp.client_exceptions.ClientError,  # <----------
    ChecksumError,
)
```

**Minimal Complete Verifiable Example**:

```python
fs.get("/this/path/does/not-exist")
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by martindurant** [comment]
Yes, sounds like a regression. Do you happen to have time to implement logic which checks for a return code first, before falling back to retries for generic errors? Is there any case in which 404 (and others) *should* be retriable?

**Comment by oliverwm1** [comment]
I also ran into this issue. Another option is to be more specific about the types of `aiohttp.client_exceptions.ClientError` that should be retried: https://github.com/dask/gcsfs/issues/316#issuecomment-829536474. But hard to know off-hand which of those should/shouldn't be retried.

**Comment by martindurant** [comment]
I would be happy to see alternative strategies, but - as you say - tricky to know exactly what set to use. Also, the exact messages given by the backend may change time to time and generally don't indicate whether the server things retrying is appropriate.

**Comment by mouradmourafiq** [comment]
I was a bit slow to respond, we have made a small change to the [function's logic](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/fs/gcs.py#L61) on our end and we can make a PR to include to the changes upstream. 

We also changed the behavior of some [blocking functions](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/fs/gcs.py#L138).

**Comment by martindurant** [comment]
Please do make a PR, but keep the retry and aiofiles separate. Er, that would make tow PRs :)
