### ISSUE TITLE
Cache is inconsistent after creating a bucket with mkdir.

### ISSUE THREAD

**Issue by baszalmstra** [dask/gcsfs#413]
**What happened**:

After creating a new bucket through the `mkdir` function, calling `fs.exists` with the bucketname reports `False`. `fs.buckets` also doesn't contain the new bucket.

Calling `fs.invalidate_cache` fixes the issue for `fs.buckets` but `fs.exists` still reports `False`. Adding a single file to the bucket yields `True` for `fs.exists` with just the bucket name.

**What you expected to happen**:

I would expect the new bucket to at least be included in `fs.buckets`. The documentation states that `fs.exists` determines if a *file* exists so I'd be ok with that not returning the `True` for just the bucket.

**Minimal Complete Verifiable Example**:

```python
bucket_name = "super_awesome-bucket-N4me"
if f"{bucket_name}/" not in fs.buckets:
    fs.mkdir(bucket_name)
```

This will raise: "gcsfs.retry.HttpError: You already own this bucket. Please select another name., 409"

**Anything else we need to know?**:

Nope

**Environment**:

- Dask version: `2021.8.1`
- Python version: `Python 3.8.10`
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): Conda

**Comment by baszalmstra** [comment]
Why was this issue closed? Has it been solved?

**Comment by martindurant** [comment]
I might be wrong? Would you please try and see if it's still there?
