### ISSUE TITLE
Managing multiple authentication tokens 

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#43]
I regularly access Google cloud services with two different google accounts.  I typically switch between them by using `gcloud auth login` and then selecting the different account.  However, even after doing so the `gcsfs` library is finding connection information for my other account.  What logic does gcsfs use?  I'm interested in tracking down from where it's getting its tokens.

**Comment by martindurant** [comment]
There is a cache of successfully generated tokens https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L315
That came before the ability to use 'cloud' or 'default' credentials, so we could choose to only cache other types, or make the cache optional. The workaround would be `GCSFileSystem.tokens.clear()` or remove the offending one(s).

**Comment by mrocklin** [comment]
OK, that explains things.  Thanks for the quick answer @martindurant !
