### ISSUE TITLE
Feature Request: Support Text IO

### ISSUE THREAD

**Issue by asford** [dask/gcsfs#52]
It would be valuable to support the standard Text I/O interface in gcsfs for use as a standalone, file-like library. The current behavior requires binary IO, which is not directly compatible with some standard tools (eg. `json`).

For example:

````
import json
import gcsfs

fs = gcsfs.GCSFileSystem(...)
an_obj = {"foo" : "bar"}

with fs.open("bucket/path", "w") as of:
    json.dump(an_obj, of)
````

raises `NotImplementedError`.

While it's possible to workaround via `io.TextIOWrapper`, it would be best to expose a `GCSFile` in text-mode in order to provide support for gcsfs-specific api extensions on the file object.

````
import json
import gcsfs

fs = gcsfs.GCSFileSystem(...)
an_obj = {"foo" : "bar"}

with fs.open("bucket/path", "wb') as of:
    json.dump(an_obj, io.TextIOWrapper(of))
````

**Comment by asford** [comment]
For clarity, particularly for anyone looking to use `gcsfs` alone, the `dask.bytes.core.OpenFileCreator` interface can be used to access this interface with under a `TextIOWrapper`.

**Comment by martindurant** [comment]
Certainly, seem easy enough to implement should `'b'` should not be in the mode, I guess within `GCSFileSystem.open` rather than `GCSFile.__init__`? 
Note that there is already some similar logic in dask.bytes.core.OpenFile, used, for instance, by dak.bag.to_textfile.
