### ISSUE TITLE
Credentials should be resolved from metadata service, if available, in default case.

### ISSUE THREAD

**Issue by asford** [dask/gcsfs#54]
### Report

I'm seeing intermittent errors using `gcsfs==0.3.0` in a `dask.distributed` cluster that, I believe, are due to an error in credential resolution. Briefly, when writing a large number of partitions to gcs via the `dask.bag.to_textfiles` interface, a number of work partitions failed with the log message:

````
Enter the following code when prompted in the browser:

....

 Traceback (most recent call last):
  File "/home/fordas/.conda/envs/dev/lib/python3.5/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/fordas/.conda/envs/dev/lib/python3.5/site-packages/gcsfs/core.py", line 597, in __setstate__
    self.connect()
  File "/home/fordas/.conda/envs/dev/lib/python3.5/site-packages/gcsfs/core.py", line 249, in connect
    raise RuntimeError("Waited too long for browser"
RuntimeError: Waited too long for browserauthentication.
````

However a number of the work partitions completed successfully. This occured while using multithreaded workers, so I assume that *some* race condition in token retrieval triggered the browser-based authentication flow. Modifying the filesystem interface in `dask.bytes.core` appeared to resolve the issue:

````
import dask.bytes
import gcsfs

import functools

org_fs = dask.bytes.core._filesystems['gcs']
wrapped_fs = functools.partial(org_fs, token="cloud")


dask.bytes.core._filesystems['gs'] = wrapped_fs
dask.bytes.core._filesystems['gcs'] = wrapped_fs
````

### Credential Resolution

Credential resolution in the default case (i.e. `GCSFileSystem(token=None)`) should resolve credentials from the default service account, rather than falling back to the oauth device flow, if the internal metadata service is available. ~~I'm not familiar with the [oauth2client.client.GoogleCredential.get_application_default()](https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L302) interface currently used in `master`, but if that interface queries instance metadata by default then this is a "doc bug" to clarify this behavior in the gcsfs interface.~~ The `oauth2client.GoogleCredential.get_application_default` interface appears to provide a token for the GCE Service account when invoked on a GCE instance and does not profive the "refresh_token" expected by `gcsfs`'s token refresh logic. This poison's `gcsfs`'s token cache and blocks authorization if `token=None` mode is used from a `GCE` instance.

### Error Handling & Auth in Dask

Pending the behavior clarification above, it seems strange to me that `dask` would invoke `gcsfs` in a mode that *could* require interactive authorization. I believe `gcsfs` should support a `headless` authorization mode which resolves credentials from (a) the `~/.gcs_tokens` token cache (b) the `gcloud` application default credentials and (c) instance metadata, but provides an informative error if interactive oauth would be required, then register this mode (rather than the current `token=None` mode) with dask. 

This would allows users to authenticate manually via the current token=`None` mode, then utilize the cached token for all further access.

**Comment by martindurant** [comment]
Have you tried using `storage_options={'project': 'myproject', 'token': 'cloud'}` in `to_textfiles`?

**Comment by asford** [comment]
I haven't tried that specifically, as I can't (in my case) couple storage configuration to the call to `to_textfiles`. The advantage of dask's approach is that the implementation can, in principle, specify different output targets via the path alone. Accommodating a scenario where I can specify an output file as `gs://my-bucket/output_dir/output.*.json` in the cloud and `~/output_dir/output.*.json` locally, without needing to modify my job code, is relatively important.

I think a small number of tweaks to the credential behavior could enable this. Would you mind if I opened a few tracking issues, with the intention of submitting a PR?

**Comment by martindurant** [comment]
@asford , sure we of course welcome suggestions and PRs.
Note that dask does support URLs like s3's `'s3://id:secret@bucket/path'`, so that could be done for gcsfs; but in general I agree that sensible defaults are a good idea too.

**Comment by asford** [comment]
Would the `headless` option described above be an acceptable solution? Given #56, I would envision an implementation that (in order of priority).

1. Resolves default credentials via the `oauth2client`. (Ideally resolving to user credentials have been established by `gsutil` or the service account.)
2. Resolves credentials from a cached token.
3. Resolves service credentials via internal metadata.
4. Falls back to unauthenticated api access.

**Comment by mrocklin** [comment]
I'm not qualified to say what a good policy is here (I don't have enough on-the-ground experience here) but just wanted to say that your engagement on this problem (and this repository generally) would be quite welcome.

**Comment by martindurant** [comment]
@asford , after conversations, I think I agree with your order of preference, for the default case of `token=None`. The options for token='cloud', token='anon' (new) and token='file'/{refresh: token} should still be respected as before.
I'll make this a separate PR which will likely conflict with the debug statements in #57
