### ISSUE TITLE
Connect to GCSFS anonymously

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#56]
I would like to set up GCSFuse in a docker container pointing to a read-only public bucket.  This container will not have any Google authentication by default.  Is it possible to create a `GCSFileSystem` without associating it to a google account and without using `token='cloud'`?

**Comment by martindurant** [comment]
It seems that yes it is possible, so long as the bucket has read access for allUsers. If the header access token, `gcs.header['Authorization']` is `None`, you get anonymous access. There is no way to get that with the current implementation of `__init__`. We could have a new `anon=` keyword, or allow `token='anon'`
