### ISSUE TITLE
`oauth2client` is deprecated.

### ISSUE THREAD

**Issue by asford** [dask/gcsfs#60]
*Ancillary issue that would likely be linked to #59*

As per [the module documentation](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) `oauth2client` is officially deprecated in favor of [`google-auth`](https://google-auth.readthedocs.io). As `google-auth` is an officially support project with a stable API, any further development of the `gcsfs` authorization system should target this library.

The current oauth implementation should likely replaced via a standard implementation using `google-auth` for token managment and the related [`google-auth-oauthlib.flow`](http://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html) for device authorization.

**Comment by martindurant** [comment]
Note that google-auth is available on conda-forge (as noarch in the latest version), but not yet on the anaconda channel.

**Comment by asford** [comment]
Is general availability on the anaconda channel a blocking requirement for any dependency?

**Comment by mrocklin** [comment]
No, it's more a signal that we should push on Anaconda.  Doing so now in company communication channels.

**Comment by martindurant** [comment]
No, gcsfs is also only on conda-forge - just making a note of it.
