### ISSUE TITLE
release

### ISSUE THREAD

**Issue by martindurant** [dask/gcsfs#63]
A new release is due following recent activity.

Need to update the client id/secret used for browser-based authentication.

Consider including fuse (#53 ) and directory (#57 ) work.

**Comment by mrocklin** [comment]
cc @asford who might have thoughts on what should be done before a new
release goes out.

**Comment by asford** [comment]
@martindurant Would you consider the current auth changes ready for release or do we need further testing?

If they're baked my vote would be to push those out immediately, with a potential quick follow up for #57.

**Comment by martindurant** [comment]
@asford Yes, I think it should be released. If you think that you can work on the directories PR, then I would wait for that.

**Comment by asford** [comment]
I'm still driving on the directory cache PR, but think it will require some work to develop the tests and work though the exposed API. Unfortunately, this isn't my primary project so I can't guarantee a finished date on that PR, though I'm targeting later this week.

That said, I'm *really* excited about the auth updates you've already made, so I suppose my bias would be to ship that as `0.0.4` immediately, then follow up with `0.0.5` to include the updated cache support soon afterward.

**Comment by martindurant** [comment]
https://github.com/conda-forge/gcsfs-feedstock/pull/2

**Comment by martindurant** [comment]
done
