### ISSUE TITLE
Objects not processed

### ISSUE THREAD

**Issue by martindurant** [dask/gcsfs#77]
@asford https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L559 - should this not be moved to the line above like `"items": [self._process_object(bucket, i) for i in items],` ? As it is, the `items` are being processed and then ignored.

**Comment by asford** [comment]
Yes, this is not well expressed in the current implementation. `_process_object` performs an in-place update of the input object dict as well as returning the modified input dict. This is obviously surprising behavior, as one would expect the function to either modify the object in-place *or* return a modified copy of the object.

The current implementation does function, as https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L559 is evaluated for the side-effect of updating the object listing, but should be changed. I'll open a PR.

**Comment by martindurant** [comment]
OK, got it. I'll remove the `items =` part at some point then, so I don't get confused again.
