### ISSUE TITLE
Use versioneer

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#81]
When using gcsfs in master it is difficult to detect what commit I'm on.  Any thoughts on switching to using versioneer for versions?  Dask and distributed both do this and could serve as models.

cc @martindurant @rabernat

**Comment by martindurant** [comment]
Personally, I find versioneer annoying and a hindrance rather than a help. That might reflect mistaken assumptions when I've tried to use it in the past. So long as releases are regular, I'm not sure it can add much, people will usually install from conda (stable) or master (dev).

**Comment by mrocklin** [comment]
It is useful when people operate on bleeding edge because they are easily
able to verify their version from python.

Pragmatically this is coming up in
https://github.com/pangeo-data/pangeo/issues/117#issuecomment-368097075
where gcsfs is not up to date, despite having pip installed from git
master.  I suspect that it *didn't *actually update because the version
numbers between installed and git master were the same.

If this is the problem then I can resolve it by forcing pip to reinstall,
but at the moment I actually don't know how to verify that this is the
problem because I don't know which version was actually installed.

**Comment by mrocklin** [comment]
This is coming up again.  I need to test to see which commit a bleeding edge environment is using.  I don't know how to do this today except by finding and looking through source code on the remote machine.

**Comment by martindurant** [comment]
How about [pbr](https://docs.openstack.org/pbr/latest/user/features.html) ?

**Comment by martindurant** [comment]
(in any case, the change is important enough that I will make a real release)

**Comment by mrocklin** [comment]
No thoughts on PBR.  I don't know it well enough to have an opinion.  I
have a slight preference for versioneer just because that seems to be what
most people use nowadays and so it is easier to find people to diagnose
issues with it.  That being said if you're maintaining this and you prefer
pbr then that seems like the right choice.

**Comment by martindurant** [comment]
#93 - that was easier than I thought.
