### ISSUE TITLE
ImportError: cannot import name 'FUSE'

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/gcsfs#95]
I've got osxfuse installed, fusepy and gcsfs installed. When i run 

`gcsfuse --help` I get `ImportError: cannot import name 'FUSE'`. 

Is there another dependency I need to run this on OSx?

**Comment by martindurant** [comment]
`FUSE` is a class within module `fuse`, which is the main part of `fusepy`. I have `fusepy` version 2.0.4, but the specific version requirement hasn't been investigated.

**Comment by martindurant** [comment]
I notice that gcsfuse appears to be running in py27, but pandas (and ipython) is in py36.

**Comment by jgerardsimcock** [comment]
Thank you @martindurant. 

We are good now
