### ISSUE TITLE
`Bad address` error with gcsfuse

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/gcsfs#96]
Creating new issue to keep things separated. 

I am trying to mount a bucket on google cloud instance. I'd like to be able to do an `xr.open_mfdataset` from the bucket. Ultimately, the intent is to store the data on a bucket in zarr. I can seemingly mount the bucket  but I am unable to actually do any file operations.

<img width="546" alt="screen shot 2018-04-09 at 10 00 06 am" src="https://user-images.githubusercontent.com/6101444/38519892-dfd8e38e-3bdc-11e8-9cd5-820daab7163c.png">

https://github.com/dask/gcsfs/issues/89
https://github.com/pangeo-data/pangeo/issues/202

I understand this is experimental software. What path's should I consider to enable this workflow? If I can make progress, I am happy to improve this and make prs.

**Comment by martindurant** [comment]
You should add `--verbose` to the gcsfuse call to see if there is any helpful information.

**Comment by jgerardsimcock** [comment]
I am not sure what to make of this, honestly. 

<img width="538" alt="screen shot 2018-04-09 at 10 12 20 am" src="https://user-images.githubusercontent.com/6101444/38520444-8857b4e4-3bde-11e8-8a42-a31c414c57f5.png">

**Comment by martindurant** [comment]
You could also try `-v -v` to get *more* output. I would guess that the default login does not have the right permission and you need to pass the token/project to gcsfuse.

**Comment by jgerardsimcock** [comment]
@martindurant thank you! `project-id` and `token` were needed.
