### ISSUE TITLE
FUSE mkdir: cannot create directory

### ISSUE THREAD

**Issue by bnaul** [dask/gcsfs#98]
```
root@fusetest-xlwl4:/src# touch test_mount/testf  # writing files works
root@fusetest-xlwl4:/src# ls test_mount
testf
root@populationgen-xlwl4:/src# mkdir test_mount/testdir
mkdir: cannot create directory ‘test_mount/testdir’: No such file or directory
```

I'm not sure if this is a known limitation of `gcsfuse` or maybe GCS itself, but there does seem to be a `mkdir` function...?

EDIT: whoops looks like that's only on master, that would explain it 😬
Using the latest master I instead get:
```
mkdir: cannot create directory ‘test_mount/testdir’: Bad address
```

**Comment by martindurant** [comment]
It is a known limitation, which #97 made some attempt to fix, but did not get all the way. The code is relatively simple, but the concept of directories in GCS a little nebulous.
