### ISSUE TITLE
Can't access public bucket without credentials

### ISSUE THREAD

**Issue by bnaul** [dask/gcsfs#99]
On master (`ccb779d3e2054310dcff0e4308fe38acfe5784f6`) in an environment with no Google credentials (`python:3.6.4` Docker image):

```
# this works
In [2]: gcsfs.GCSFileSystem(token='anon').open('gs://gcp-public-data-landsat/index.csv.gz').read(1)
Out[2]: b'\x1f'

# but this doesn't
In [3]: gcsfs.GCSFileSystem().open('gs://gcp-public-data-landsat/index.csv.gz').read(1)
_call exception: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc9bdd5b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
# ... several pages of these logs
# ... then several pages of tracebacks; finally:
RefreshError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc9b785eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

It seems that the default auth should be falling back on `anon`; I guess this type of exception is not being caught properly? Additionally, if the `anon` method did eventually succeed, it might be preferable to suppress the logs during the initial failure+retries.

**Comment by martindurant** [comment]
I would guess that method='cloud' is apparently succeeding - this is being run on a google cluster - but then the metadata service doesn't actually have valid credentials available.

One thing that we could do, is, upon connecting, attempt to get info or data from a key that is known to be accessible to all. That would force the credentials to be tried "for real". This could always be an optional check_connection=True parameter.

**Comment by martindurant** [comment]
Can you please check with #100 ?
If this fixes the problem, I am prepared to quickly release gcsfs, so that your PR on pandas can go ahead without the untidy anon logic.

**Comment by bnaul** [comment]
This doesn't fix the problem for me, but I have a bit better idea what's going on now. The above was just running locally, not on Google cloud, but you're right that token is being set to `cloud`.

```
In [6]: fs = gcsfs.GCSFileSystem(token='cloud')
In [7]: fs.session
Out[7]: <google.auth.transport.requests.AuthorizedSession at 0x7f0e177ad358>
```

It looks like the logic in `connect(method=None)` expects `fs.session` to be None if the credentials are invalid, but the failure is instead deferred until you try to actually use them. Maybe checking another property instead would catch this, e.g. (using the above)
```
In [12]: fs.session.credentials.valid
Out[12]: False
```

**Comment by martindurant** [comment]
I don't quite see how that happens, but I have added a line to reset the session if the connection apparently fails. Checking for `credentials.valid` won't work because, until the first use of the credentials, they were likely be expired and not (yet) valid. Please correct me if I am wrong.

**Comment by bnaul** [comment]
Makes sense; #100 with one modification (see comments) now works for me:
```
In [4]: gcsfs.GCSFileSystem().open('gs://gcp-public-data-landsat/index.csv.gz').read(1)
Out[4]: b'\x1f'
```
